### PR TITLE
add support for offix useOfflineMustation

### PR DESCRIPTION
**Pull request by auryn31**
Add Support to create offix offline mutations

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @auryn31 ! 
Do you think it must be as a new plugin? maybe it could be integrated into the existing `react-apollo` plugin ?

**Comment by auryn31** [comment]
Hy @dotansimha,
I thought about extending the current `react-apollo`, but I didn't want to bring the offix dependency into this plugin.
But if you prefere the other way, we could bring it in there.

**Comment by dotansimha** [comment]
I see. Can you please just verify that this plugin can work together with the existing `react-apollo` plugin in the same output? Because I think we can keep it separated, but this could be an extension to the other types generated by the existing plugin.

**Comment by auryn31** [comment]
Thanks for the response. It works wit the Apollo plugin. I use it together with this one :)

**Pull request merged**
