### PR TITLE
fix(plugin: graphql-requests): Fix type errors in auto-generated methods

### PR DESCRIPTION
**Pull request by remew**
I created PR(#5414) few days ago.
but it cause some type errors. (https://github.com/dotansimha/graphql-code-generator/pull/5414#issuecomment-767648010, #5459)
This PR fixes that errors.

### CODE REVIEW

**Comment by joeynimu** [comment]
Is this PR good to go? I am facing the same issue.

```
Module '"../node_modules/graphql-request/dist/types.dom"' declares 'HeadersInit' locally, but it is not exported.
```
It would be nice to have this merged. In the meantime, what's the workaround?

**Comment by remew** [comment]
@joeynimu Hi, there is a workaround in [this issue](https://github.com/dotansimha/graphql-code-generator/issues/5459).

**Comment by ardatan** [comment]
Thanks @remew !

**Comment by dohomi** [comment]
when will this merge land in a next version? Thanks

**Pull request merged**
