### PR TITLE
fix: 2 security vulnerabilities

### PR DESCRIPTION
**Pull request by nbouvrette**
Related issue: https://github.com/dotansimha/graphql-code-generator/issues/8154

Fixes the following security issues:

- undici before v5.8.0 vulnerable to CRLF injection in request headers - https://github.com/advisories/GHSA-3cvr-822r-rqcc
- undici before v5.8.0 vulnerable to uncleared cookies on cross-host / cross-origin redirect - https://github.com/advisories/GHSA-q768-x9m6-m9qp

@graphql-codegen/cli@2.11.0 depends on
  @whatwg-node/fetch  <=0.0.2, which depends on vulnerable versions of undici
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

No - please whoever merges this, run your tests.

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
Thanks @nbouvrette can you please add a `patch` changeset explaining your change

**Comment by nbouvrette** [comment]
@saihaj not too sure what you mean exactly? I don't know much about this repo to be honest - it might be easier if you take over the change on your end

**Comment by ardatan** [comment]
We use `changesets` to manage versioning, prepare changelogs and release new versions.
https://github.com/dotansimha/graphql-code-generator/pull/8153#issuecomment-1197294692
As described in this comment, you need to run `yarn changeset` to create a changeset with `patch` version bump then we can release it.

**Comment by charlypoly** [comment]
@nbouvrette fixing this vulnerability also needs to update some dependencies on `graphql-tools`, we'll take over from here in https://github.com/dotansimha/graphql-code-generator/pull/8155

**Comment by nbouvrette** [comment]
@charlypoly thanks! Sorry I wasn't more useful :) was just updating my dependencies yesterday and tried to help

**Pull request closed without merging**
