### PR TITLE
Expose fetcher (with `exposeFetcher` config) in `typescript-react-query` plugin 

### PR DESCRIPTION
**Pull request by paolotiu**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description
This pull request adds an option to export each query's fetcher.

Related # (issue)
 #5526

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Unit test
- [x] Local Manula test

**Test Environment**:
- OS: Ubuntu-20.04 (WSL2)

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @paolotiu ! I pushed a minor fix for tests (you had `it.only`) and added a `changeset` file.

**Comment by paolotiu** [comment]
> Thanks @paolotiu ! I pushed a minor fix for tests (you had `it.only`) and added a `changeset` file.

Thanks for catching that! Must've forgotten to remove it 😅. Thank you for accepting the PR. Have a great day!

**Comment by amak07** [comment]
@paolotiu thanks for this fix! finally found your update here after pulling my hair out past couple days. Quick question - how can I verify that I'm getting prefetched data? I'm seeing an empty "data" object in the log output.  Also, it seems that Tanner (the guy who created react-query) provided a solution for a "bug" in serializing data coming back from the fetch query, hence the JSON.parse(JSON.stringify) expression.

`export const getStaticProps: GetStaticProps = async (): Promise<{
  props: { dehydratedState: DehydratedState };
}> => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(useGetReviewsQuery.getKey(), () =>
    useGetReviewsQuery.fetcher(graphqlRequestClient)
  );

  const hello = JSON.parse(JSON.stringify(dehydrate(queryClient)));

  console.log("static props", hello.queries[0].state);

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};`

any insight is appreciated!

**Comment by paolotiu** [comment]
@amak07 Are you able to check the keys of the prefetched query vs the keys of the query inside the component? I'm suspecting it's related to issue #6191

**Pull request merged**
