### PR TITLE
fix: SWC plugin error handling

### PR DESCRIPTION
**Pull request by JesseVelden**
The API for SWC changed a bit for error handling between my original PR and the updated SWC crate. So this PR should fix panics in the SWC plugin.

Related #9057

@saihaj I'm not sure how the format of the CHANGELOG.md should be, so can you add that or explain that? 😁

### CODE REVIEW

**Comment by n1ru4l** [comment]
@JesseVelden any idea about this? https://github.com/dotansimha/graphql-code-generator/pull/9060

**Review by YassinEldeeb — APPROVED** [review]
looks good

**Comment by saihaj** [comment]
hey @JesseVelden can you please rebase this PR?

**Comment by JesseVelden** [comment]
> hey @JesseVelden can you please rebase this PR?

Thanks for notifying me! I've updated it =)

**Pull request merged**
