### PR TITLE
change the client-preset generated template.

### PR DESCRIPTION
**Pull request by ElvisUpUp**
## Description

[Related issue](https://github.com/dotansimha/graphql-code-generator/issues/8762)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by saihaj — APPROVED** [review]
looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.

**Comment by ElvisUpUp** [comment]
> looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.

Sorry for reply late because I am sick early. I'll try to add a changeset now.

**Comment by ElvisUpUp** [comment]
> looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.

I have already add a changeset for this.

**Comment by saihaj** [comment]
> > looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.
> 
> I have already add a changeset for this.

looks like there are few ESM test issues here? @ElvisUpUp

**Comment by ElvisUpUp** [comment]
> > > looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.
> > 
> > 
> > I have already add a changeset for this.
> 
> looks like there are few ESM test issues here? @ElvisUpUp

fixed it already.

**Comment by ElvisUpUp** [comment]
> > > > looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.
> > > 
> > > 
> > > I have already add a changeset for this.
> > 
> > 
> > looks like there are few ESM test issues here? @ElvisUpUp
> 
> fixed it already.

@saihaj can I update branch with merge request now?

**Comment by saihaj** [comment]
> > > > > looks great! thanks for the fix. Can you please add a changeset for this. You can [learn more](https://github.com/dotansimha/graphql-code-generator/pull/8763#issuecomment-1362623836) about changeset here.
> > > > 
> > > > 
> > > > I have already add a changeset for this.
> > > 
> > > 
> > > looks like there are few ESM test issues here? @ElvisUpUp
> > 
> > 
> > fixed it already.
> 
> @saihaj can I update branch with merge commit now?

great work will get a rebase out shortly!

**Pull request merged**
