### PR TITLE
[SEC] Replace cross-undici-fetch with @whatwg-node/fetch. Fixes security vulnerability introduced by undici < 5.8.0

### PR DESCRIPTION
**Pull request by gustaff-weldon**
## Description
Replaces `cross-undici-fetch` with `@whatwg-node/fetch`.
 
The `@whatwg-node/fetch` seem to be a renamed version of the former which no longer depends on the vulnerable `undici` version.

Related issue: #8132

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Untested, happy to learn how to test.

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by charlypoly — APPROVED** [review]

**Comment by charlypoly** [comment]
@gustaff-weldon, thank you for handling this! ⚡

**Comment by gustaff-weldon** [comment]
@charlypoly you are welcome, do you have any guesses when this will be released on npm?

**Comment by charlypoly** [comment]
> @charlypoly you are welcome, do you have any guesses when this will be released on npm?

@gustaff-weldon, it is released as part of `@graphql-codegen/cli@2.10.0` 📦

**Comment by SimenB** [comment]
0.0.2 is too old, it still depends on a vulnerable version of `undici`

**Comment by charlypoly** [comment]
This security vulnerability has been properly fixed by @ardatan in `@graphql-codegen/cli@2.11.2` 📦

**Pull request merged**
