### PR TITLE
Update fragment generation for better TS perf

### LINKED ISSUE #5991: Typechecking fragments is very slow
Hi @dotansimha - long time no chat.

I have been investigating our typescript typechecking performance recently and have narrowed down a huge time-sink to be these fragments, as the the complex type comparison with the big nested object takes a lot of time.
image

Attaching a coarse pic of a TS trace of ours (feel free to ping me for greater breakdown of the trace).
image
All the circled time is spent typechecking these objects.

**Describe the solution you'd like**
I am attaching a PR with a pretty simple fix. Basically, since we autogenerate these types, we really dont need to typechecking them again (since we are confident in this toolchain :)). Instead, we will just cast these objects to the right type so places relying on them still see them correctly, but we dont pay the cost of confirming them.

Please let me know if you are ok with this approach. If so, I will fix up all the failing tests (since changing output, will need to change the goldens to match).

**Describe alternatives you've considered**
Alternatively, for the same reasons described above, we could really just straight emit the .d.ts and .js files mimicing what TSC will do anyway. Since that seems like a larger change with more consequences than I am aware, i think this approach should be considered for the future but is not implemented now.

### PR DESCRIPTION
**Pull request by markjm**
Related #5991 

## Description
Above ticket has motivation. Initially opening this PR to show example for discussion in issue.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Current test suite is sufficient - will need updates once we come to agreement on issue

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]
If I get this correctly, we'll now have `export const TestDocument = { ... } as unknown as DocumentNode<...>` instead of `export const TestDocument: DocumentNode<...> = { ... }`, right? 

Seems totally valid, and if it does solve the performance issue, we can go with that.

**Comment by ardatan** [comment]
@markjm Could you fix the tests so we can merge and release :)

**Comment by markjm** [comment]
> If I get this correctly, we'll now have `export const TestDocument = { ... } as unknown as DocumentNode<...>` instead of `export const TestDocument: DocumentNode<...> = { ... }`, right?
> 
> Seems totally valid, and if it does solve the performance issue, we can go with that.

thats correct. Given agreement, I will go head an fix the tests soon.

**Comment by markjm** [comment]
@dotansimha I think this is ready to go with test fixes, but builds cant run without approval

**Comment by markjm** [comment]
Fixed dev-test!

**Comment by ardatan** [comment]
@markjm Do you have any idea why Windows tests are failing?

**Comment by ardatan** [comment]
Next time, could you merge our master into your branch with `git rebase` instead of `git merge`? It would be better in order to keep git history consistent.

**Comment by markjm** [comment]
@ardatan hm, I am on windows and am not able to reproduce the git diff issue. It looks like it is not using the changes present in this PR. its like its using the old code to generate these files.

Longshot: could pipeline caching of yarn's node_modules possibly be getting messed up due to symlinks of a yarn workspace?

image

**Comment by markjm** [comment]
> Next time, could you merge our master into your branch with `git rebase` instead of `git merge`? It would be better in order to keep git history consistent.

yea sorry I can do that. I am used to squash merges and so have historically merged, but I can rebase instead

**Comment by markjm** [comment]
thanks for merging. Sorry for the branching confusion

**Comment by ardatan** [comment]
Thanks @markjm <3

**Comment by Urigo** [comment]
@markjm I would love to tweet and say thank you publicly for this PR, do you have a Twitter handle?
Should I also tag MS or Teams or something?

**Comment by m-rutter** [comment]
I just experimented with this PR and its reduced whole project type check times from cold by 20%, and improved IDE responsiveness quite a bit when in codgen files or files that have imports from them.

Thanks @markjm for figuring this out.

**Comment by markjm** [comment]
Awesome to hear @m-rutter 

> @markjm I would love to tweet and say thank you publicly for this PR, do you have a Twitter handle?
> Should I also tag MS or Teams or something?

I don't have a public twitter, feel free to shout out @MicrosoftTeams -- appreciate the recognition!

**Comment by kenotron** [comment]
https://twitter.com/kenneth_chau/status/1395125097984188416?s=20 :)

**Comment by Urigo** [comment]
https://twitter.com/UriGoldshtein/status/1395381326744850433?s=20 (I saw there was another tweet here but you removed the comment?)

**Comment by aprilrd** [comment]
I really appreciate the work on TS performance. Is there a technical reason why this PR only improved `@graphql-codegen/typescript-document-nodes`? If not, I might try finding time for other plugins.

**Comment by markjm** [comment]
@aprilrd no reason, this is just the place I saw was most impacting especially for the repo I work in. I'm sure there are more improvements available in the area!

**Comment by aprilrd** [comment]
Appreciate the response. Thanks!

**Pull request merged**
