### PR TITLE
C sharp reserved keywords

### PR DESCRIPTION
**Pull request by cklam2**
Attempt to solve the issue with reserved keywords, see #4248. Names will now be prefixed with `@` when it is a keyword. 

Note that the list of keywords is static. If Microsoft decides to extend the list then we'd have to manually update the list. 

Note that changes are based on the `c-sharp-improvements` branch which is not yet merged to master. Hopefully that is not a big issue.

### CODE REVIEW

**Comment by dotansimha** [comment]
@cklam2 can you please rebase? :) 
Thanks!

**Comment by cklam2** [comment]
@dotansimha thanks. I will first make a change in the code. Want to make use of that convertName feature instead. Will mention you again when rebased and ready for review/merge.

**Comment by cklam2** [comment]
Updated the code and rebased onto master. Also took the chance to clean up the unit test so format looks cleaner and bit more in line with other unit tests. Btw, new unit tests for this bug are also added.
@dotansimha code is ready for review/merge, thanks.

**Comment by dotansimha** [comment]
@cklam2 I merged this one, it includes all changes from https://github.com/dotansimha/graphql-code-generator/pull/4264 as well, right?

**Comment by cklam2** [comment]
@dotansimha thanks for the merge!
#4264 is not included in this one. I rebased that branch onto the new master.

Btw, I see a branch "revert-4250-c-sharp-reserved-keywords"?

**Comment by dotansimha** [comment]
@cklam2 thanks! The revert branch was a mistake :) 
I merged #4264 as well. Thank you so much !

**Pull request merged**
