### PR TITLE
Avoid input optionals

### PR DESCRIPTION
**Pull request by ekfn**
Relevant to  https://github.com/dotansimha/graphql-code-generator/issues/1885

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @ekfn ! 
@kamilkisiela can you please review?

**Comment by thefliik** [comment]
That moment when you run into a problem only to find someone else has already created a PR to solve it 😃  🎉 

This being said, is it appropriate for this API to be different from the [`declarationKind` config](https://graphql-code-generator.com/docs/plugins/typescript#declarationkind-declarationkindconfig) API ?

Specifically,  `declarationKind` has a single config argument. You can either provide a single string value, or you can provide a config object which allows different configs depending on the GQL schema element type. Rather than letting `avoidOptionals` accept a single boolean or a config object, I see this PR adds a separate config argument, `avoidInputOptionals`. 

On the one hand, `avoidOptionals` only applies to two GQL schema types: `FieldDefinition` and `InputValueDefinition` while `declarationKind` can apply to `ScalarsDefinition`, `InputObjectTypeDefinition`, `ObjectTypeDefinition`, etc. Letting the `avoidOptionals` config argument accept an object may make people think they can configure other definition types rather than just Field and InputValue.

On the other hand, implementing this change by keeping a single `avoidOptionals` argument, that accepts either a config object or a boolean, will create a more consistent API and is potentially more "future proofed", as other keys could be added to the config object in the future. Admittedly, I can't think of anything else that might be added in the future.

All this is to say that I, personally, would vote for something like this to be the API:

```yml
config:
  avoidOptionals:
    object: true
    inputValue: false

# OR

config:
  avoidOptionals: true
```

It's not a big deal though.

**Comment by dotansimha** [comment]
Thank you @ekfn ! 
What do you think about @thefliik 's suggestion? I think it's a bit more nice API.

**Comment by ekfn** [comment]
Yes, the API is a bit nicer and has better backward compatibility, although I am not familiar with all parts of this repo, I will try to implement it.

**Comment by ekfn** [comment]
@dotansimha I've updated pull request

**Comment by dotansimha** [comment]
That's perfect! Thank you @ekfn ! how was the experience of working on this? the code base was easy to understand?

**Comment by ekfn** [comment]
@dotansimha the code base is good, TS was very helpful, but the tests were a bit confusing (I think they do not cover all test cases).
Glad that I was able to help. :)

**Pull request merged**
