### PR TITLE
Support iterable for TypeScript resolver returns

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/dotansimha/graphql-code-generator/issues/1298.

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @blakeembrey ! 
Can you please explain your implementation? I think I'm missing something there. 
`isReturn` is a way to tell if you are generating the return type of a resolver?
Also, do you think it's relevant only for resolvers package? Maybe stating `Iterable` might be useful for the type itself (and then the resolvers package will also have it).

**Comment by kamilkisiela** [comment]
I don't know if `graphql` supports `Iterable` in every resolver and not only in subscription related ones. If that's something you're interested in, we can add Iterable to the `SubscriptionResolver` union so it applies to all subscription resolvers without having to pass a boolean anywhere.

**Comment by blakeembrey** [comment]
@kamilkisiela It does, like I said in my linked issue GraphQL uses `iterall` which means it supports all iterables. You might be confusing async iterators with regular iterators here.

> isReturn is a way to tell if you are generating the return type of a resolver?

Yes.

> Also, do you think it's relevant only for resolvers package? 

I believe so, since it's only valid for the return type in resolvers for GraphQL JS.

**Comment by dotansimha** [comment]
Thanks @blakeembrey , we implemented the your changes in the recent refactor :)

**Pull request closed without merging**
