### PR TITLE
[Do not merge] Initial flow support

### PR DESCRIPTION
**Pull request by blackxored**
This is very barebones initial Flow support, mostly copied from the TS single file generator. 
I was able to generate a file without Flow complains for the 3 schemas in dev-test and 2 custom ones. Haven't been able to test the client schema generation part yet. 

I would very much like some help getting a better test setup to ensure all of this is correct, currently is really hard to tests (i.e either write all the tests by hand or hack the cli, in addition, provided schemas are not complex enough to ensure correctness it seems).

- [x] Add single file to list of generators
- [ ] Add multiple file
- [x] Type support
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by dotansimha** [comment]
That's great, @blackxored !! Thank you! 
I will review is soon :)

**Comment by dotansimha** [comment]
Looks good @blackxored . 

How was the experience of writing Handlebars template? Because I'm adding a new feature that will allow to add custom output processors (per generator) that will allow us to write custom JS code to generate the template (instead of Handlebars).

Also, do you think that there are missing Handlebars helpers that could make it simpler? 

Thank you!

**Comment by blackxored** [comment]
I think definitely being able to write your code in JS for some advanced scenarios is gonna be needed at some point. However, I do like the simplicity of Handlebars templates, since there's basically such a minimal API so people can get started really easy. 
The scenarios I have in mind (generating UI, backend, etc) would probably need that more likely than not.

**Comment by dotansimha** [comment]
@blackxored any chance we can complete this? 😊

**Comment by dotansimha** [comment]
Closing for now.

**Pull request closed without merging**
