### PR TITLE
Implement watch mode

### LINKED ISSUE #379: Watch mode using watchman?
I must say it becomes a bit of a pain over time to always have to run the command whenever I make changes to my queries. I am thinking if it would be possible to utilize watchman for this. I might even take a stab at it if it's something you consider a good idea?

### PR DESCRIPTION
**Pull request by FredyC**
Alright, here goes very basic and crude implementation. I have checked it against my project and it's working very nicely. 

I should probably add some tests, but I am not entirely sure about it. Would need to mock filesystem most likely and I can imagine it would be failing on CI anyway since Watchman is usually not installed there. What do you think @dotansimha?

PS: I added `semi` option to prettier config here. I hope you don't mind, it was driving me crazy to write those semicolons manually everywhere :)

Fixes #379

### CODE REVIEW

**Comment by dotansimha** [comment]
Looks good @FredyC! I think we should also watch for the schema file (in case of a local or introspection file)

**Comment by FredyC** [comment]
@dotansimha Yea, I think I agree, it's just I have never used this portion of the tool and never really understood what is it good for :)

**Comment by dotansimha** [comment]
@FredyC You can just use `--schema` value, and use code similar to that to make sure it's a local file: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/codegen.ts#L159-L159 , and then just watch this file as well.

**Comment by dotansimha** [comment]
Thanks @FredyC !

**Pull request closed without merging**
