### PR TITLE
feat: Add stripIgnoredCharacters option (visitor-plugin-common) - continued

### PR DESCRIPTION
**Pull request by JanStevens**
## Description

Adds a new stripIgnoredCharacters: boolean option to client-side-base-visitor that removes redundant characters (like line-breaks, whitespaces, etc.) from the query strings.

In the linked issue, I originally proposed doing .replace(/\s+/g, ' ').trim() on the strings, but that turned out to be an unreliable approach as it would fail to cover a number of cases:

- It doesn't remove extraneous whitespaces that are not consecutive, so like `query ( $var : Int! )` (should become `query ($var: Int!)`) or more commonly `query { foo bar }` (should become `query{foo bar}`).
- If you have a string literal inside the query, that contains more than one consecutive space or line breaks, it removes those but it obviously shouldn't.

This all means a GraphQL-specific minifier is actually needed to do this reliably,
Happily I found out there's a built-in function in [graphql-js](https://github.com/graphql/graphql-js) for this very task! stripIgnoredCharacters — see https://github.com/graphql/graphql-js/issues/1523, which does precisely this.

## Related # (issue)

Related to #5616 and continuation of #8322

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I've added a test in `ts-documents.spec.ts`, but I'm not really sure this is the best location. I looked at how other options are tested but it seems there are barely any tests for the client visitor.

**Test Environment**:

- OS: Mac M1
- `@graphql-codegen/...`: latest
- NodeJS: v16.18

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

This is the continuation of PR https://github.com/dotansimha/graphql-code-generator/pull/8322 all credits go to @aradalvand

### CODE REVIEW

**Comment by charlypoly** [comment]
Hi @JanStevens,

Thank you for continuing @aradalvand's work here.
Please know that while adding a new option is a tempting solution, we aim to solve this issue https://github.com/dotansimha/graphql-code-generator/issues/8296 at a higher level (as part of the [v3 roadmap](https://github.com/dotansimha/graphql-code-generator/issues/8296), by rewriting codegen's core).

Considering our existing plan to address the issues linked to the amount of generated code, we don't plan to add this feature to `visitor-plugin-common`.

Also, we don't judge this issue as blocking since:
- we recommend not committing generated files (especially types)
- we now provide a new preset (`client-preset`) that generates only types instead of hooks or SDKs, reducing the bundle's impact
- as stated above, we plan to rewrite the core only to emit used types

**Comment by JanStevens** [comment]
Hi @charlypoly,

Thanks for the swift answer, v3 sounds great! Concerning committing generated files: It's a bit hard to have a working typescript setup in various stages of CI / local development. Especially if those types are changing a lot, it could introduce typescript errors when performing production deploys so we rather have them committed.

Down the line I think that using the `stripIgnoredCharacters` is still an important feature to include as it greatly reduce the size of the generated.

I'll take a look at the `client-preset`

Regards

**Comment by aradalvand** [comment]
@JanStevens This is not about the types though, it's about the strings, strings aren't wiped out in the compliation step like types are (obviously) and so I don't see how your bullet points apply to this PR.

**Comment by JanStevens** [comment]
> @JanStevens This is not about the types though, it's about the strings, strings aren't wiped out in the compliation step like types are (obviously) and so I don't see how your bullet points apply to this PR. Correct me if I'm wrong.

My reply was not concerning this PR as it can be closed, but rather at the comment from @charlypoly regarding V3 ;)

**Comment by aradalvand** [comment]
My bad, I meant to mention @charlypoly... Made a mistake. I don't think this PR should've been closed. We need this option anyway.

**Comment by aradalvand** [comment]
> No worries, by all means reopen it 😉

I can't, you're the author 😁

I think you should keep it open unless @charlypoly decides otherwise. In [this comment of mine](https://github.com/dotansimha/graphql-code-generator/pull/8489#issuecomment-1280836015) I was trying to point out, in response to @charlypoly, that I'm not sure how his points were relevant to this particular feature, this PR/feature is concerned with the strings, and not the types; unless I've misunderstood something here.

Why shouldn't this PR be merged now, @charlypoly?

**Comment by charlypoly** [comment]
> @charlypoly Would love for you to clarify.

Sure!
We now recommend using the `client-preset` for most GraphQL client (ex: front-end) use-cases because this new preset provides the smoothest developer experience and lightest code generator (for now, but will be improved in the future with a rewrite of the core of codegen).
While the `client-preset` still generates document nodes as follows:

```ts
const documents = {
    "\n  query allFilmsWithVariablesQuery($first: Int!) {\n    allFilms(first: $first) {\n      edges {\n        node {\n          ...FilmItem\n        }\n      }\n    }\n  }\n": types.AllFilmsWithVariablesQueryDocument,
    "\n  fragment FilmItem on Film {\n    id\n    title\n    releaseDate\n    producers\n  }\n": types.FilmItemFragmentDoc,
};
```

it heavily relies on TypeScript function overloads on the provided `graphql()` helper, meant to be used to replace `graphql-tag`:

```ts
const documents = {
    "\n  query allFilmsWithVariablesQuery($first: Int!) {\n    allFilms(first: $first) {\n      edges {\n        node {\n          ...FilmItem\n        }\n      }\n    }\n  }\n": types.AllFilmsWithVariablesQueryDocument,
    "\n  fragment FilmItem on Film {\n    id\n    title\n    releaseDate\n    producers\n  }\n": types.FilmItemFragmentDoc,
};

export function graphql(source: "\n  query allFilmsWithVariablesQuery($first: Int!) {\n    allFilms(first: $first) {\n      edges {\n        node {\n          ...FilmItem\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query allFilmsWithVariablesQuery($first: Int!) {\n    allFilms(first: $first) {\n      edges {\n        node {\n          ...FilmItem\n        }\n      }\n    }\n  }\n"];
export function graphql(source: "\n  fragment FilmItem on Film {\n    id\n    title\n    releaseDate\n    producers\n  }\n"): (typeof documents)["\n  fragment FilmItem on Film {\n    id\n    title\n    releaseDate\n    producers\n  }\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
```

As you might guess, stripping all ignored characters will break the TS function overloading here.

While this PR still applies to existing plugins, we are right now focusing our efforts on bringing new features to the v3 roadmap and fixing blockers in existing versions.

**Comment by JanStevens** [comment]
> 

You could still use `stripIgnoredCharacters` in both `documents` and `graphql` to make it condenser 🤔 

I'm looking forward for the new approach, right now I can't really grasp how to use this with for example `graphql-request` but I guess as v3 comes a long more documentation / migration will become clear

**Comment by charlypoly** [comment]
> You could still use `stripIgnoredCharacters` in both `documents` and `graphql` to make it condenser 🤔

Yes but then your GraphQL Operations would need to be written in a condensed way at the source too.



> I'm looking forward for the new approach, right now I can't really grasp how to use this with for example `graphql-request` but I guess as v3 comes a long more documentation / migration will become clear

You will find a complete example here: https://github.com/dotansimha/graphql-code-generator/tree/master/examples/front-end/react/graphql-request and new documentation here: https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue

**Comment by JanStevens** [comment]
> You will find a complete example here: https://github.com/dotansimha/graphql-code-generator/tree/master/examples/front-end/react/graphql-request and new documentation here: https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue

Cool, thanks for the docs. We currently have a setup with `.graphql` files and `fragments` as `.graphql` files (ex: `event.fragments.graphql`). For larger projects this makes it easier to have reusable (and discoverable) fragments / queries. Would that be supported in v3? I don't necessarily see how that would work 🤔.

**Comment by aradalvand** [comment]
I can't wrap my head around this supposed v3 `client-preset` thing, that's object whose keys are document strings, and whose values are... what?!

**Comment by charlypoly** [comment]
> Cool, thanks for the docs. We currently have a setup with `.graphql` files and `fragments` as `.graphql` files (ex: `event.fragments.graphql`). For larger projects this makes it easier to have reusable (and discoverable) fragments / queries. Would that be supported in v3? I don't necessarily see how that would work 🤔.

The `client-preset` only support inline graphql tag based definitions, using the exposed `graphql()` helper.



> I can't wrap my head around this supposed v3 `client-preset` thing, the `document` constant there is an object whose keys are document strings, and whose values are... what?!
> Makes no sense.

The `documents` is mapping string literals (your GraphQL definitions) to their typing equivalent (`TypedDocumentNode` types)

In short, we use the literal GraphQL definition strings to build function overloads on `graphql()` that will return the proper typing.

**Comment by aradalvand** [comment]
v3 has been released and this aspect of the library hasn't changed at all, therefore I think this PR is still relevant.
@JanStevens Could you please consider reopening this?

**Comment by aradalvand** [comment]
@charlypoly Could you please respond?

**Pull request closed without merging**
