### PR TITLE
fix(react-query): ensure mutationKey is an array

### LINKED ISSUE #7281: Fix(react-query): ensure mutationKey is always array
**Describe the bug**
React Query is requiring queryKeys and mutationKeys to always be an array.  see:
https://github.com/tannerlinsley/react-query/issues/2919

**To Reproduce**
Use with React Query v4 (currently alpha) will throw type errors.

**Expected behavior**
Use an array for the keys instead of a string.  i.e. `['mystring']` instead of `'mystring'`

**Environment:**
any

**Additional context**
v4 is currently in pre-release and will become more pressing once released.  This is a backwards-compatible upgrade... arrays have always been an acceptable key.

### PR DESCRIPTION
**Pull request by jonathanstanley**
fix: react query is requiring all keys to be an array

## Description

Related #7281 react query will require all keys be an array.  see: https://github.com/tannerlinsley/react-query/issues/2919

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
The change is simple and backwards compatible because arrays have always been valid keys.

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dotansimha** [comment]
@jonathanstanley thanks !! 

can you please run `yarn changeset` and add a patch fix for this? 
Also, can you please try to run `yarn generate:examples` to regenreate all example files? 

^ this should fix ci and we can merge and release

**Comment by jonathanstanley** [comment]
@dotansimha Completed those commands as you asked.  I'm not entirely certain if this should be considered a PATCH or a MINOR.  Although the change is backwards compatible with react-query, it is possible some have hardcoded their systems to expect `myQuery` instead of `['myQuery']`.

**Comment by charlypoly** [comment]
Hi @jonathanstanley 

I agree with you, this change might be breaking for people directly on `getKey()` methods for anything else than passing it to ReactQuery.
Also, the upcoming ReactQuery v4 will introduce many other changes that might ripple in plugin changes that will not be backward compatible.

The best solution here might be to add a new plugin option `targetMajorVersion` or `reactQueryMajor` that would behave as a feature flag to enable or not new changes linked to a target major (here: `4`).
Your change would be part of the `targetMajorVersion >= 4`.

WDYT?

**Comment by jonathanstanley** [comment]
Thanks @charlypoly  .  

I could see it both ways.  A flag to `targetMajorVersion` would certainly work.  In my case, I had some custom hardcoded keys which very easy to recognize and fix.  My entire conversion from v3 to v4 was maybe an hour and among the easiest major updates i've dealt with.  I haven't seen any other conflicts with this plugin. For those reasons, I lean towards keeping it simple here and just making an appropriate semver change.  Perhaps I should just redo the changeset as a minor and we can at least get this part done?

**Comment by charlypoly** [comment]
@jonathanstanley let's proceed with a minor bump on the plugin

**Review by charlypoly — CHANGES_REQUESTED** [review]
@jonathanstanley some tests are failing because snapshots had not been updated 👀 

cf: https://jestjs.io/docs/snapshot-testing#updating-snapshots

**Comment by jonathanstanley** [comment]
can you take it from here?  i'm not familiar with this package build/ci processes

**Comment by charlypoly** [comment]
> can you take it from here? i'm not familiar with this package build/ci processes

@jonathanstanley The unit-tests were not updated, cf: https://github.com/dotansimha/graphql-code-generator/pull/7282/commits/87ff406e0a32e437242418e65ffdcb4e17ed4ea2

The test setup is pretty simple to run locally, you just need to do the following (at the root of the project):

```bash
yarn
yarn build
yarn test packages/plugins/typescript/react-query  # will fail
# fix tests
yarn test --updateSnapshot packages/plugins/typescript/react-query
yarn test packages/plugins/typescript/react-query # should pass!
```

**Review by charlypoly — APPROVED** [review]
Good to go 🚀

**Pull request merged**
