### PR TITLE
New template: `typescript-graphql-request`

### PR DESCRIPTION
**Pull request by dotansimha**
A new plugin, for NodeJS developers, that generates SKD for `graphql-request` based on schema and operations. 

Usage example:

```yml
schema: https://countries.trevorblades.com/
documents: 'src/graphql/**/*.graphql'
generates:
  src/sdk.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
```

```graphql
query continents {
  continents {
    name
    countries {
      ...CountryFields
    }
  }
}
fragment CountryFields on Country {
  name
  currency
}
```

And then to use the SDK:

```ts
import { GraphQLClient } from 'graphql-request';
import { getSdk } from './sdk'; // THIS FILE IS GENERATED

async function main() {
  const client = new GraphQLClient('https://countries.trevorblades.com/');
  const sdk = getSdk(client);
  const { continents } = await sdk.continents(); // This is fully typed, based on the query
  
  console.log(`GraphQL data:`, continents);
}

main().catch(e => {
  console.error(e);
});

```

An example repo could be found here: 
https://github.com/dotansimha/graphql-codegen-graphql-request-example

### CODE REVIEW

**Comment by lnmunhoz** [comment]
This is awesome!

**Comment by P4sca1** [comment]
This looks very promising! <3

**Comment by schmod** [comment]
This is great! Thanks so much!

**Comment by artalar** [comment]
That's exactly what I was looking for! Thx.

**Comment by dancegit** [comment]
This is amazing, I am new to this.. as I understand it its not easily combined with e.g. vuex-orm.. I guess I do not need the vuex-orm in this case..? .. I do not want to write models for vuex orm thats all.. lol.. I rather generate stuff and use it.. I will give it a shot.. thanks !!!

**Comment by dotansimha** [comment]
@dancegit I'm not familiar with `vuex-orm` at all, can you please share an example for the input GraphQL schema and the output you'll need in order to integrate it with `vuex-orm`?

**Comment by Manubi** [comment]
how would it work with swr? [swr.now.sh](url)
`import { request } from 'graphql-request'

const API = 'https://api.graph.cool/simple/v1/movies'
const fetcher = query => request(API, query)

function App () {
  const { data, error } = useSWR(
    `{
      Movie(title: "Inception") {
        releaseDate
        actors {
          name
        }
      }
    }`,
    fetcher
  )
  // ...
}`

**Comment by dotansimha** [comment]
@Manubi It seems like you need more than just this plugin, because you need to generate the `useSWR` with typings, right? 
I think it could be done only with a new plugin

**Comment by ColeTownsend** [comment]
Yeha I'd be interested in this

**Comment by dotansimha** [comment]
@ColeTownsend @Manubi feel free to open a new issue for that if it's still relevant. It seems like a new plugin (or at least configuration for the existing one) is needed to support this use case.

**Comment by bstro** [comment]
for future google wanderers, I just stumbled across this: https://github.com/croutonn/graphql-codegen-plugin-typescript-swr re: `swr`

**Pull request merged**
