### PR TITLE
Update add plugin with output section selection

### PR DESCRIPTION
**Pull request by AnotherHermit**
Add functionality to add plugin so that it is possible to select which output section the text should end up in.

This supports such use cases such as wrapping the output in a namespace, etc.

### CODE REVIEW

**Comment by dotansimha** [comment]
That's perfect, @AnotherHermit ! And you also fixed https://github.com/dotansimha/graphql-code-generator/issues/1896 ;)

**Comment by benquarmby** [comment]
Just upgraded to 1.3.0 of this plugin. The configuration shape changed without backwards compatibility. This was technically a breaking change as well as a new feature. Ideally it would have bumped to 2.0.0.

**Comment by dotansimha** [comment]
@benquarmby can you please explain why it's breaking? You can still specify a string, and it will work as before.

**Comment by benquarmby** [comment]
Old configuration:
```
overwrite: true
schema:
  - "../../graphql/graphql-*/index.gql"
documents: null
generates:
  ./src/generated.ts:
    plugins:
      - add:
          - "/* eslint-disable */"
```
New configuration:
```
overwrite: true
schema:
  - "../../graphql/graphql-*/index.gql"
documents: null
generates:
  ./src/generated.ts:
    plugins:
      - add:
          content:
            - "/* eslint-disable */"
```
Trying to use the old config on 1.3.0 throws an error and requires code changes to fix.

**Comment by AnotherHermit** [comment]
Which version did you use before? And what does the error say?

**Comment by benquarmby** [comment]
```
-        "@graphql-codegen/add": "1.1.0",
-        "@graphql-codegen/cli": "1.1.0",
-        "@graphql-codegen/typescript": "1.1.0",
+        "@graphql-codegen/add": "1.3.0",
+        "@graphql-codegen/cli": "1.3.0",
+        "@graphql-codegen/typescript": "1.3.0",
```

When using the old config with 1.3.0 we see an `Add plugin, missing content` message
image

**Comment by AnotherHermit** [comment]
If I am not mistaken I think there was kind of a bug (#1896) introduced in 1.2.0 that made it difficult to support the kind of input you had in your config. The problem being that if you have any top level config (not related to the add plugin) in that file the parser would throw an error. I tried to make the fix as backwards compatible as possible, but did not handle all cases since the migration path is pretty simple.

**Comment by benquarmby** [comment]
Got it. Yeah, seems to be related. We've moved forward by being more explicit with the config (adding `content` property).

**Pull request merged**
