### PR TITLE
New website, better docs (based on nextjs & @theguild/docs) 

### PR DESCRIPTION
**Pull request by B2o5T**
- I squashed all commits from this [PR](https://github.com/dotansimha/graphql-code-generator/pull/6766) to make rebase easy (first commit)
- Use last Next.js v12
- Typescripify all files
- Configure ESLint with `next` config
- Make `LiveDemo` component works
- Prettify all docs, found a lot of typo in `generated-config` folder

### CODE REVIEW

**Comment by dotansimha** [comment]
@B2o5T , I think the-guild-docs doesn't play well with next v12? can you please take a look at https://github.com/dotansimha/envelop/pull/911 ? 

Also, I added you as contributor, so you can use a local branch in this repo instead of a fork.

**Comment by dotansimha** [comment]
`typescript` plugin page still 404?

**Comment by B2o5T** [comment]
@dotansimha fixed! Also now code highlighting must work for `yml`, `gql`, `diff`, `java`, `c#` blocks

**Comment by B2o5T** [comment]
I fixed this error on new docs
image

**Review by dotansimha — APPROVED** [review]

**Pull request merged**
