### PR TITLE
feat(apollo-client-helpers): export StrictTypedTypePolicies

### LINKED ISSUE #6318: Expose stricter TypedTypePolicies without apollo's native TypePolicies
**Is your feature request related to a problem? Please describe.**
Currently `TypedTypePolicies` is exposed as a union of typed policies from schema and apollo's native untyped `TypePolicies`:
```typescript
export type TypedTypePolicies = TypePolicies & {
   UserType?: Omit<TypePolicy, "fields" | "keyFields"> & {
       keyFields?: false | UserTypeKeySpecifier | (() => undefined | UserTypeKeySpecifier),
       fields?: UserTypeFieldPolicy,
    }
}
```
Here `UserType` is our own type, while `TypePolicies` is defined like this:
```typescript
export declare type TypePolicies = {
    [__typename: string]: TypePolicy;
};
```
This makes it prone to error if I were to change the existing type policies or if I were to add a field that doesn't exist, e.g.
```typescript
const policies: TypedTypePolicies = {
    UserType: {...},
    UserType2: {....},
    SomethingElse: {....}
}
```
No typescript error is generated here since `TypedTypePolicies` allows any string key.

**Describe the solution you'd like**
I would like `TypedTypePolicies` to be stricter than that and disallow any fields that don't exist in the schema.
It would help to have to separate types exported from the generated code, e.g.

```typescript
export type StrictTypedTypePolicies = {
   UserType?: Omit<TypePolicy, "fields" | "keyFields"> & {
       keyFields?: false | UserTypeKeySpecifier | (() => undefined | UserTypeKeySpecifier),
       fields?: UserTypeFieldPolicy,
    };
};

export TypedTypePolicies = StrictTypedTypePolicies & TypePolicies;
``` 

This would be backwards compatible and wouldn't require adding any options and would allow to choose a stricter type.

**Describe alternatives you've considered**

**Additional context**

Thanks! 😄

### PR DESCRIPTION
**Pull request by duncanbeevers**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Strengthen the `TypePolicies` type protections by narrowing allowed keys to know types.
Define and export `StrictTypedTypePolicies`
Export backwards-compatible union of `StrictTypedTypePolicies` and original very-loose `TypePolicies`
Update documentation example to use `StrictTypedTypePolicies`

Related #6318

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Demonstration of flagged `Unknown` key

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Tested generated output in real project
- [ ] Tested with jest and examined snapshot changes

**Test Environment**:
- OS: macOS
- `@graphql-codegen/apollo-client-helper`: 1.1.10
- NodeJS: v14.17.4

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by duncanbeevers** [comment]
The documentation is updated to use `StrictTypedTypePolicies` in the example.

It is rare but possible to need `TypedTypePolicies`. Perhaps the documentation here should include some information as to when you would choose one or the other.

Particularly, this [Overriding root operation types](https://www.apollographql.com/docs/react/caching/cache-configuration/#overriding-root-operation-types-uncommon) section of the Apollo documentation covers instances where `StructTypedTypePolicies` would be insufficient.

@MargaretKrutikova @dotansimha Do you have opinions on how detailed the documentation here should be?

**Comment by dotansimha** [comment]
Thank you @duncanbeevers ! This is really great! 

> @MargaretKrutikova @dotansimha Do you have opinions on how detailed the documentation here should be?

Not really, I think we can start with the basics and if needed we can improve later.

**Review by dotansimha — APPROVED** [review]

**Comment by MargaretKrutikova** [comment]
Thanks a lot for your PR, @duncanbeevers! 😄  It is going to be really nice to have this change in the library ❤️

**Comment by duncanbeevers** [comment]
I don't know if there's anything else necessary for this. I made it a draft so we could have some discussion.

I'll un-draft it and we can figure out next steps.

**Comment by duncanbeevers** [comment]
I rebased this against `origin:master` and squashed it down to a single commit. Should be good-to-go.

**Pull request merged**
