### PR TITLE
feat(flow): flow-operations tries to spread inexact objects #8000

### PR DESCRIPTION
**Pull request by Athelian**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description
Flow-operations tries to spread exact/inexact objects into the same merged object which leads to flow errrors.

Related dotansimha/graphql-code-generator-community#198 (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):
https://flow.org/try/#0FAFwngDgpgBAJABQJYGMDWAeA8gJyQcyQDsAuGLAIwCsoUQAaGAaSjAGczKa6A+GAXnhcAsgEMISDC3aMprHgAo0ZaQEoBfOAFEANlAC2UIiAAqkKNjyEijaTx4BuYKHMwcUAGZR3RFLEEA3gA+ogD8ZBQA9pF6okRBAL7O4NAwHjqRAO5Y0DiiIEiRRGxmqYHAMDAAdDUBMAD69SlGooZkAOQASp7eRn7tMAn0FdU1iKiY7l4+fowjwTBhZABUMIk8wEnAKEVsIDAgUHtk6Vk53vmFxaX+MAGNzUStUGQARN3TfVCvjKJkIDgAK5QBJAA

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS: Linux
- Flow: 0.181.2
- `@graphql-codegen/flow-operations` version: ^2.2.13

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by charlypoly** [comment]
Hi!

All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
<details>
<summary>Community plugins:</summary>

- `@graphql-codegen/typescript-react-apollo`
- `@graphql-codegen/typescript-graphql-request`
- `@graphql-codegen/typescript-apollo-angular`
- `@graphql-codegen/typescript-apollo-client-helpers`
- `@graphql-codegen/typescript-react-query`
- `@graphql-codegen/typescript-urql`
- `@graphql-codegen/named-operations-object`
- `@graphql-codegen/urql-introspection`
- `@graphql-codegen/flow-resolvers`
- `@graphql-codegen/typescript-vue-apollo`
- `@graphql-codegen/typescript-rtk-query`
- `@graphql-codegen/flow-operations`
- `@graphql-codegen/typescript-msw`
- `@graphql-codegen/typescript-mongodb`
- `@graphql-codegen/typescript-type-graphql`
- `@graphql-codegen/jsdoc`
- `@graphql-codegen/typescript-vue-urql`
- `@graphql-codegen/kotlin`
- `@graphql-codegen/typescript-vue-apollo-smart-ops`
- `@graphql-codegen/java`
- `@graphql-codegen/c-sharp-operations`
- `@graphql-codegen/hasura-allow-list`
- `@graphql-codegen/typescript-stencil-apollo`
- `@graphql-codegen/relay-operation-optimizer`
- `@graphql-codegen/typescript-oclif`
- `@graphql-codegen/java-resolvers`
- `@graphql-codegen/java-apollo-android`
- `@graphql-codegen/flutter-freezed`

</details>

### Please move your PR by following these steps:

From your current PR branch:
- git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
- git fetch codegen-community
- git push codegen-community

Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.

Thank you!

**Comment by Athelian** [comment]
> Hi!
> 
> All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
> 
> Community plugins:
> ### Please move your PR by following these steps:
> From your current PR branch:
> 
> * git remote add codegen-community [git@github.com](mailto:git@github.com):dotansimha/graphql-code-generator-community.git
> * git fetch codegen-community
> * git push codegen-community
> 
> Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.
> 
> Thank you!

Thank you, but I got permission denied with these steps:
```
ath@ath-aurora:~/graphql-code-generator$ git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
ath@ath-aurora:~/graphql-code-generator$ git fetch codegen-community

remote: Enumerating objects: 765, done.
remote: Counting objects: 100% (506/506), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 765 (delta 362), reused 506 (delta 362), pack-reused 259
Receiving objects: 100% (765/765), 421.43 KiB | 592.00 KiB/s, done.
Resolving deltas: 100% (465/465), completed with 57 local objects.
From github.com:dotansimha/graphql-code-generator-community
 * [new branch]          community                  -> codegen-community/community
 * [new branch]          main                       -> codegen-community/main
 * [new branch]          renovate/auto-bind-5.x     -> codegen-community/renovate/auto-bind-5.x
 * [new branch]          renovate/babel-monorepo    -> codegen-community/renovate/babel-monorepo
 * [new branch]          renovate/change-case-all-1.x -> codegen-community/renovate/change-case-all-1.x
 * [new branch]          renovate/changesets-changelog-github-0.x -> codegen-community/renovate/changesets-changelog-github-0.x
 * [new branch]          renovate/lodash-4.x        -> codegen-community/renovate/lodash-4.x
 * [new branch]          renovate/major-graphql-tools-monorepo -> codegen-community/renovate/major-graphql-tools-monorepo
 * [new branch]          renovate/node-18.x         -> codegen-community/renovate/node-18.x
 * [new branch]          renovate/oclif-command-1.x -> codegen-community/renovate/oclif-command-1.x
 * [new branch]          renovate/reduxjs-toolkit-1.x -> codegen-community/renovate/reduxjs-toolkit-1.x
 * [new branch]          renovate/urql-introspection-1.x -> codegen-community/renovate/urql-introspection-1.x
ath@ath-aurora:~/graphql-code-generator$ 
ath@ath-aurora:~/graphql-code-generator$ git push codegen-community

ERROR: Permission to dotansimha/graphql-code-generator-community.git denied to Athelian.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by charlypoly** [comment]
> > Hi!
> > All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
> > Community plugins:
> > ### Please move your PR by following these steps:
> > From your current PR branch:
> > 
> > * git remote add codegen-community [git@github.com](mailto:git@github.com):dotansimha/graphql-code-generator-community.git
> > * git fetch codegen-community
> > * git push codegen-community
> > 
> > Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.
> > Thank you!
> 
> Thank you, but I got permission denied with these steps:
> 
> ```
> ath@ath-aurora:~/graphql-code-generator$ git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
> ath@ath-aurora:~/graphql-code-generator$ git fetch codegen-community
> 
> remote: Enumerating objects: 765, done.
> remote: Counting objects: 100% (506/506), done.
> remote: Compressing objects: 100% (136/136), done.
> remote: Total 765 (delta 362), reused 506 (delta 362), pack-reused 259
> Receiving objects: 100% (765/765), 421.43 KiB | 592.00 KiB/s, done.
> Resolving deltas: 100% (465/465), completed with 57 local objects.
> From github.com:dotansimha/graphql-code-generator-community
>  * [new branch]          community                  -> codegen-community/community
>  * [new branch]          main                       -> codegen-community/main
>  * [new branch]          renovate/auto-bind-5.x     -> codegen-community/renovate/auto-bind-5.x
>  * [new branch]          renovate/babel-monorepo    -> codegen-community/renovate/babel-monorepo
>  * [new branch]          renovate/change-case-all-1.x -> codegen-community/renovate/change-case-all-1.x
>  * [new branch]          renovate/changesets-changelog-github-0.x -> codegen-community/renovate/changesets-changelog-github-0.x
>  * [new branch]          renovate/lodash-4.x        -> codegen-community/renovate/lodash-4.x
>  * [new branch]          renovate/major-graphql-tools-monorepo -> codegen-community/renovate/major-graphql-tools-monorepo
>  * [new branch]          renovate/node-18.x         -> codegen-community/renovate/node-18.x
>  * [new branch]          renovate/oclif-command-1.x -> codegen-community/renovate/oclif-command-1.x
>  * [new branch]          renovate/reduxjs-toolkit-1.x -> codegen-community/renovate/reduxjs-toolkit-1.x
>  * [new branch]          renovate/urql-introspection-1.x -> codegen-community/renovate/urql-introspection-1.x
> ath@ath-aurora:~/graphql-code-generator$ 
> ath@ath-aurora:~/graphql-code-generator$ git push codegen-community
> 
> ERROR: Permission to dotansimha/graphql-code-generator-community.git denied to Athelian.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Hi,

yes sorry, you need to fork the new repo, I've updated the instructions above.

**Comment by saihaj** [comment]
[Hey! this plugins has moved to our community repo https://github.com/dotansimha/graphql-code-generator-community/tree/main/packages/plugins/flow/operations

### Please move your PR by following these steps:

From your current PR branch:
- git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
- git fetch codegen-community
- git push codegen-community

Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.

Thank you!](https://github.com/dotansimha/graphql-code-generator-community/tree/main/packages/plugins/typescript/generic-sdk)

**Pull request closed without merging**
