### PR TITLE
Fluter freezed v3.0.0

### PR DESCRIPTION
**Pull request by Parables**
## Description

[chore(deps): update dependency typescript to v4.8.3](https://github.com/dotansimha/graphql-code-generator/commit/8ef73858384e44e8328b61fddcc49ae92779df5f)

### CODE REVIEW

**Comment by Parables** [comment]
This really took longer than expected. I drifted away into other projects hence the long delay in resolving this simple issue #8286

@n1ru4l sincere apologies

**Comment by n1ru4l** [comment]
hey @Parables thank you for this PR, could you have a look at the failing tests (ignore the eslint/prettier issue)

**Comment by Parables** [comment]
> hey @Parables thank you for this PR, could you have a look at the failing tests (ignore the eslint/prettier issue)

@n1ru4l, I hardly saw this coming but I really have less free time available but that is not to say that I am not going to keep on updating this plugin.... I just need to squeeze out some free time. 

Please don't give up on me and this plugin cause I won't either....

Thank you so much for the support and patience... means a lot to me and I am sincerely grateful

**Comment by charlypoly** [comment]
Hi @Parables!

All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
<details>
<summary>Community plugins:</summary>

- `@graphql-codegen/typescript-react-apollo`
- `@graphql-codegen/typescript-graphql-request`
- `@graphql-codegen/typescript-apollo-angular`
- `@graphql-codegen/typescript-apollo-client-helpers`
- `@graphql-codegen/typescript-react-query`
- `@graphql-codegen/typescript-urql`
- `@graphql-codegen/named-operations-object`
- `@graphql-codegen/urql-introspection`
- `@graphql-codegen/flow-resolvers`
- `@graphql-codegen/typescript-vue-apollo`
- `@graphql-codegen/typescript-rtk-query`
- `@graphql-codegen/flow-operations`
- `@graphql-codegen/typescript-msw`
- `@graphql-codegen/typescript-mongodb`
- `@graphql-codegen/typescript-type-graphql`
- `@graphql-codegen/jsdoc`
- `@graphql-codegen/typescript-vue-urql`
- `@graphql-codegen/kotlin`
- `@graphql-codegen/typescript-vue-apollo-smart-ops`
- `@graphql-codegen/java`
- `@graphql-codegen/c-sharp-operations`
- `@graphql-codegen/hasura-allow-list`
- `@graphql-codegen/typescript-stencil-apollo`
- `@graphql-codegen/relay-operation-optimizer`
- `@graphql-codegen/typescript-oclif`
- `@graphql-codegen/java-resolvers`
- `@graphql-codegen/java-apollo-android`
- `@graphql-codegen/flutter-freezed`

</details>

### Please move your PR by following these steps:

From your current PR branch:
- git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
- git fetch codegen-community
- git push codegen-community

Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.

Thank you!

**Comment by Parables** [comment]
Thanks for notifying me of the changes.

**Comment by Parables** [comment]
Done as requested @charlypoly 

See https://github.com/dotansimha/graphql-code-generator-community/pull/14

**Pull request closed without merging**
