### PR TITLE
feat: allow use of Observables on subscriptions with generic-sdk

### PR DESCRIPTION
**Pull request by onhate**
Allow the use of Observables on subscription operations for Generic SDK

```
config:
  usingObservableFrom: "import Observable from 'zen-observable';"
OR
  usingObservableFrom: "import { Observable } from 'rxjs';"

documents: '../**/document.graphql'
generates:
  ./index.ts:
    schema: '../**/schema.graphql'
    plugins:
      - typescript
      - typescript-operations
      - typescript-generic-sdk
```

Generates a method that returns an Observable instead of a Promise.

```
...
import Observable from 'zen-observable';
OR
import { Observable } from 'rxjs';
...

export function getSdk<C>(requester: Requester<C>) {
  return {
     ...
    onX(variables?: OnXVariables, options?: C): Observable<OnXSubscription> {
      return requester<OnXSubscription, OnXVariables>(OnXDocument, variables, options);
    }
  };
}
```

When this config is enabled, the Requester response will change to this:
```
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R> | Observable<R>
```

This is an optional configuration that does not breaks existing setup.

### CODE REVIEW

**Comment by dotansimha** [comment]
This is a great idea!  Thank you for implementing this, @onhate ! 
I'll review it soon :)

**Comment by onhate** [comment]
hi @dotansimha and @ardatan, did you have the chance to review this PR?

**Comment by onhate** [comment]
@dotansimha, @ardatan  ?

**Comment by onhate** [comment]
guys, any chance we could move this PR this week? @dotansimha @ardatan

**Comment by onhate** [comment]
@dotansimha @ardatan are you there?

**Comment by ardatan** [comment]
@onhate Thanks for the PR! LGTM!

**Comment by henrique-rotava** [comment]
Great implementation @onhate ! I was looking for some solution like that.

**Comment by dotansimha** [comment]
Thanks @onhate , it looks good.
Can you please move `RawGenericSdkPluginConfig` to a new file, called `config.ts`? It will simplify the process of creating auto-generated docs for that plugins. 

Thank you :)

**Comment by onhate** [comment]
@dotansimha done!

**Comment by onhate** [comment]
@dotansimha, @ardatan is there any plan to make this available on npm soon?

**Pull request merged**
