### PR TITLE
[typescript-react-query] Pass `dataSource` as argument to `fetcher`

### PR DESCRIPTION
**Pull request by dan-lee**
## Description

This passes in the missing `dataSource` argument to `fetcher`, when `exposeFetcher: true` is set.

I am not sure about the order of arguments, for the hook it's the first argument, here it's second.
But changing the order of arguments would be a breaking change, wouldn't it?

Reported issue #6414 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Original test has been extended

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nenadfilipovic** [comment]
Yup, same problem, with provided endpoint and fetchParams inside codegen.yml it is fixed, but to use fetcher standalone this fix is needed.

**Comment by paolotiu** [comment]
Hey, @dan-lee I was about to make my own pull request, but then I saw yours. I think the datasource should be passed as the first argument since the original hook accepts it as the first argument. Although it would technically be a breaking change, current users won't be able to use the exposed fetcher since the datasource isn't an argument.

**Comment by dan-lee** [comment]
Hey @paolotiu, sorry I have been on vacation and couldn't make the changes sooner. It makes sense to change the order of arguments, as you mentioned. I just pushed it and it would be ready to merge if it's not already fixed. :)

**Comment by paolotiu** [comment]
Thanks for the fix @dan-lee! No problem at all, hope you enjoyed your vacation :)

**Comment by nenadfilipovic** [comment]
Is this ready?

**Comment by paolotiu** [comment]
It's just waiting for it to be merged.

**Comment by dan-lee** [comment]
I'd be more than happy if it got merged :)

**Comment by n1ru4l** [comment]
Hey there, there is another potential breaking change and I would like to bundle those together into a single release if possible. You could help me tremendously by adding a changeset to this pull request that showcases how this will affect end-users (ideally with a migration path) and furthermore give feedback on https://github.com/dotansimha/graphql-code-generator/pull/6611

Then I will release those two PRs together next week :)

**Review by n1ru4l — CHANGES_REQUESTED** [review]
Please add a changset as I mentioned in my comment

**Comment by paolotiu** [comment]
Hey @n1ru4l! Thanks for looking at this. Although this pr wouldn't necessarily break anything for users (since it's already broken in the first place), I agree that it would be good practice to bundle this with the other change you suggest regarding the processing of the .env variables.

**Comment by dan-lee** [comment]
Thanks for providing the changeset and merge ✌️

**Pull request merged**
