### PR TITLE
feat(typescript): support preceding comments

### PR DESCRIPTION
**Pull request by gogoyqj**
commentDescriptions: Provide true to use preceding comments as the description, eg "# comment"

### CODE REVIEW

**Comment by dotansimha** [comment]
Awesome! Thank you @gogoyqj !

**Comment by bnaoki** [comment]
Is there a config option to keep the old behavior? I use the `schema-ast` plugin to generate a master schema file and would like to keep the comments hidden (i.e. left as comments).

**Comment by gogoyqj** [comment]
@dotansimha with pleasure

**Comment by gogoyqj** [comment]
@bnaoki i'm so sorry...

**Comment by dotansimha** [comment]
@bnaoki Added `commentDescriptions` configuration in: https://github.com/dotansimha/graphql-code-generator/commit/24f12f33e60a62563d0b130392ac424316b61124 

In the next release you'll be able to do `commentDescriptions: true`.

**Pull request merged**
