### PR TITLE
Enable flattening typed document nodes

### PR DESCRIPTION
**Pull request by fehnomenal**
I wanted to completely flatten fragments.

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @fehnomenal 
Can you please share more about the use-case? I just want to understand why is it needed and how to documents it. 
Also, can you please add a `changeset`? (`yarn changeset` and it will guide you)

**Comment by fehnomenal** [comment]
Honestly, I can't really remember what the problem was but I can no longer reproduce it. Nevertheless, I think with this option the plugin is more in line with the other

**Comment by fehnomenal** [comment]
Ahh, I remember now. I use https://github.com/clentfort/urql-custom-scalars-exchange to convert ISO datetime strings to Date objects and this library does not play well with fragments. So I had the choice of patching either library and this inlining was way easier.

But inlining only the operations was not enough because now the typed documents referenced the generated types for the fragments, which no longer existed due to being inlined.

**Comment by dotansimha** [comment]
Got it, thanks @fehnomenal !

**Pull request merged**
