### PR TITLE
feat: Support including fragments when using flattenGeneratedTypes in typescript-operations

### PR DESCRIPTION
**Pull request by asmundg**
## Description

When consuming GraphQL from multiple input files, flattenGeneratedTypes will result in fragment types getting dropped.

This introduces a new option, flattenGeneratedTypesIncludeFragments, which makes the relay compiler retain all fragments when flattenGeneratedTypes is enabled, resulting in all fragment types being produced.

This doesn't affect the generated documents and only results in additional TypeScript types getting defined.

Related #7285

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Unit tests added
- [X] Tested in non-public production repo

**Test Environment**:
- OS: MacOS 11.6.1
- `@graphql-codegen/typescript-operations`: 2.2.1
- NodeJS: 17.0.1, 13.18.0

## Checklist:

- [X] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by charlypoly — CHANGES_REQUESTED** [review]
Hi @asmundg,

Thank you very much for this addition! ⚡ 

Could you please add a test for this use-case when `flattenGeneratedTypes` is `true` but `flattenGeneratedTypesIncludeFragments` is `false`? (here: `packages/plugins/typescript/operations/tests/ts-documents.spec.ts`)

Thank you!

**Comment by asmundg** [comment]
@charlypoly sure thing!

**Review by charlypoly — APPROVED** [review]

**Comment by charlypoly** [comment]
> @charlypoly sure thing!

@asmundg two unit-tests are failing in `packages/plugins/typescript/operations/tests/ts-documents.spec.ts` 👀 

➡️ https://github.com/dotansimha/graphql-code-generator/runs/5068988661?check_suite_focus=true

**Comment by asmundg** [comment]
d'oh, didn't consider merging master.

**Pull request merged**
