### PR TITLE
Proposed quickfix for unknown fragment

### PR DESCRIPTION
**Pull request by jonaskello**
This is a quickfix for #624 to allow users to continue working. 

It will simply ignore errors with message "Unknown fragment". This way we can still get the filename of every other error.  I think only the case with misspelled fragment names in spreads where the fragment is imported from another file will be not be validated with this fix.

The proper fix would be to actually resolve all the fragments.

### CODE REVIEW

**Comment by dotansimha** [comment]
Looks good. Thanks @jonaskello !

**Comment by dotansimha** [comment]
@furier We have CI that publishes alpha version. for now, you can use it with these versions:
```
Successfully published:
 - graphql-code-generator@0.13.0-alpha.106f2555
 - graphql-codegen-compiler@0.13.0-alpha.106f2555
 - graphql-codegen-core@0.13.0-alpha.106f2555
 - codegen-templates-scripts@0.13.0-alpha.106f2555
 - graphql-codegen-apollo-angular-template@0.13.0-alpha.106f2555
 - graphql-codegen-introspection-template@0.13.0-alpha.106f2555
 - graphql-codegen-typescript-mongodb-template@0.13.0-alpha.106f2555
 - graphql-codegen-typescript-react-apollo-template@0.13.0-alpha.106f2555
 - graphql-codegen-typescript-template@0.13.0-alpha.106f2555
```

**Comment by jonaskello** [comment]
Turns out this quickfix does not cover the case when a query has an argument that is only used in a fragment. The validation will correctly give a `Error: Variable "$foo" is never used in operation "FooQuery".` message. This case should be somewhat rare but I have it in my codebase...

**Comment by jonaskello** [comment]
@dotansimha Should I could try to make a new PR with a proper fix, or is someone else already working on that?

**Comment by furier** [comment]
Do you have an example?
man. 24. sep. 2018 kl. 11:09 skrev Jonas Kello <notifications@github.com>:

**Comment by jonaskello** [comment]
@furier Do you mean example where the unused variable problem will show up?

**Comment by furier** [comment]
yes

man. 24. sep. 2018 kl. 16:51 skrev Jonas Kello <notifications@github.com>:

**Comment by furier** [comment]
I have never made fragments for Queries or Mutations before only for return
types, so was interesting to see...

man. 24. sep. 2018 kl. 17:27 skrev Jonas Kello <notifications@github.com>:

**Pull request merged**
