### PR TITLE
Initial support for generating multiple files

### PR DESCRIPTION
**Pull request by dotansimha**
The general approach is to allow devlopers to write `preset`s  that can manipulate codegen execution right before executing the plugins.
Each preset can have it's own configuration, and in the future, preset will be able to do more (according to the community needs).

At the moment, the leading use-case for this is to allow to output generate a file near the source operation file. 

For example: the plugin `near-operation-file` will generate output file per each operation, in a file next to it. The way it does that is by using each input operation file and execute plugins with each operation.

This PR will also introduce a new recipe for creating your `.yml` config file, because of the dependencies between plugins. For example, `typescript` plugin will have to be executed on itself, into a separate file (`types.ts`), and then `typescript-operations` will get executed once per each operation file, and will reference the `types.ts` file.

For example:

```yml
schema: schema.graphql
generates:
    src/types.ts:
     plugins:
            - typescript
    src/: # This is the base dir
       documents: src/**/*.graphql
       preset: near-operation-file
       presetConfig:
            baseTypesPath: "src/types.ts" # Tell it where to import these from
            extension: ".generated.ts" # Tell it how to name each file
       plugins:
            - typescript-operations
            - typescript-react-apollo
```

> There are ways to make it easier and not repeating `src/types.ts`.

This will work with minimal changes to the codegen at the moment, and in the future we will expand the abilities of a "preset".

## Issues to resolve / think about
- [x] How to handle `graphql-import`?
- [x] Fix `react-apollo` missing imports for fragment document
- [x] Fix `Maybe` by importing it 
- [x] How to handle fragments?
- [x] How to handle imports? `import * as Types` or import each type?
- [x] What else preset can do?
- [x] More use-cases? 
- [x] Docs

### CODE REVIEW

**Comment by dotansimha** [comment]
Working examples are currently under `./dev-test/test-preset`. 

Currently all fragments are generated under each file, but that would change soon. The goal is to generate a file per fragment as well, and then to import the generated fragment type from it.

**Comment by const86** [comment]
Love it! In our projects we have operations interfaces next to graphql files scattered in multiple folders. This feature would help a lot.

**Comment by const86** [comment]
FYI: With this, even required operation variables are wrapped in `Maybe`:
```graphql
query foo($arg: Int!) {
  foo(arg: $arg)
}
```
becomes
```typescript
import * as Types from './types';

export type FooQueryVariables = {
  arg: Types.Maybe<Types.Scalars['Int']>
};


export type FooQuery = ({ __typename?: 'Query' } & Pick<Types.Query, 'foo'>);
```

**Comment by dotansimha** [comment]
Just noticed it, thanks @const86, I'll fix in the next commit :)

**Comment by furier** [comment]
awesome work @dotansimha!!! 👍

**Comment by mxstbr** [comment]
Getting an error when trying this:

```
Plugin "urql" requires extension to be ".tsx"!
```

This is my config, latest `canary` version of all packages:

```yaml
overwrite: true
schema: "server/src/**/*.graphql"
documents: "web/src/**/*.graphql"
generates:
  web/src/graphql/introspection-result.ts:
    plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "fragment-matcher"
  web/src/types.ts:
    plugins:
      - typescript
    config:
      immutableTypes: false
  web/src:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: "web/src/types.ts"
      extension: ".tsx"
    plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-operations"
      - "typescript-urql"
    config:
      immutableTypes: false
      withComponent: false 
      withHooks: true
  web/src/graphql/types.d.ts:
      plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-graphql-files-modules"
```

**Comment by dotansimha** [comment]
Thanks for the feedback @mxstbr , I'm on it now.

**Comment by dotansimha** [comment]
@mxstbr I tried to copy your configuration and run it in the `dev-test` directory of our repo (it has some test schemas and operations there).

Tested this `.yml` file:

```yml
overwrite: true
schema: dev-test/githunt/schema.json
documents: dev-test/githunt/**/*.graphql

generates:
  dev-test/githunt/introspection-result.ts:
    plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "fragment-matcher"

  dev-test/githunt/types.ts:
    plugins:
      - typescript
    config:
      immutableTypes: false

  dev-test/githunt/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      extension: ".tsx"
    plugins:
      - typescript-operations
      - typescript-urql
    config:
      immutableTypes: false
      withComponent: false 
      withHooks: true

  dev-test/githunt/types.d.ts:
      plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-graphql-files-modules"
```

And my output was:
```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate dev-test/githunt/introspection-result.ts
      ✔ Load GraphQL schemas
  ✔ Parse configuration
  ✔ Generate outputs
✨  Done in 0.75s.
```


Is it possible to get a way to reproduce it? (Also, can you please make sure that you are using the latest alpha from `master`? It's `1.1.4-alpha-a2d52a5f.41`)

Thank you!

**Comment by mxstbr** [comment]
Upgraded to alpha.41 and now get a different error: `web/src: Plugin "urql" with "noComponents" requires extension to be ".ts" or ".tsx"!`

These are my package versions:

```JSON
{
    "@graphql-codegen/add": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/core": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/fragment-matcher": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/introspection": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/near-operation-file-preset": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/typescript": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/typescript-graphql-files-modules": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/typescript-operations": "1.1.4-alpha-a2d52a5f.41",
    "@graphql-codegen/typescript-urql": "1.1.4-alpha-a2d52a5f.41"
}
```

This is my exact config:

```yml
overwrite: true
schema: "server/src/**/*.graphql"
documents: "web/src/**/*.graphql"
generates:
  web/src/graphql/introspection-result.ts:
    plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "fragment-matcher"
  web/src/types.ts:
    plugins:
      - typescript
    config:
      immutableTypes: false
  web/src:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: "web/src/types.ts"
      extension: ".tsx"
    plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-operations"
      - "typescript-urql"
    config:
      immutableTypes: false
      withComponent: false 
      withHooks: true
  web/src/graphql/types.d.ts:
      plugins:
      - add: |
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-graphql-files-modules"
```

**Pull request merged**
