### PR TITLE
typescript-client: Include __typename in fragments and metadata fields

### PR DESCRIPTION
**Pull request by kamilkisiela**
Fixesss (@dotansimha ~~related~~) https://github.com/dotansimha/graphql-code-generator/issues/643#issuecomment-428464025 and https://github.com/dotansimha/graphql-code-generator/issues/643#issue-363140248

### CODE REVIEW

**Comment by kamilkisiela** [comment]
I don't know if that works within fragments but I think it's enough for now

**Comment by dotansimha** [comment]
Awesome! ❤️ @kamilkisiela 
Can you please implement the same for the new plugins? (https://github.com/dotansimha/graphql-code-generator/pull/1353)

**Comment by kamilkisiela** [comment]
@dotansimha <3 of course!

**Comment by awdyson** [comment]
@kamilkisiela thanks for the work, this helped me quite a bit

Are you planning on adding `__typename` to the `typescript-server` plugin as well?
Consider this a vote for if you're on the fence 😛

**Comment by awdyson** [comment]
Playing with the canary build, I guess my true ask would be to (optionally?) add `__typename` to the `typescript` plugin.

**Pull request merged**
