### PR TITLE
Provide custom naming convention

### PR DESCRIPTION
**Pull request by ardatan**
Related to #977

- [ ] check if add new kinds
- [ ] check if all kinds are correctly used

### CODE REVIEW

**Comment by dotansimha** [comment]
@ardatan ci fails

**Comment by kamilkisiela** [comment]
@dotansimha @dotansimha @ardatan @dotansimha @ardatan

**Comment by ardatan** [comment]
@kamilkisiela @dotansimha @kamilkisiela @dotansimha 👍

**Comment by dotansimha** [comment]
@ardatan @kamilkisiela 
Looks good. Can you please update the docs?

**Pull request merged**
