### PR TITLE
feat: set input value deprecation to true

### PR DESCRIPTION
**Pull request by samchungy**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

Sets `inputValueDeprecation` to true so that the graphql plugin by default returns information on input value deprecations

Related #7768 (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Set `inputValueDeprecation` in `config` key to `true` in `graphql-codegen.yml`. Run project and see @deprecated annotations.
- Run with default config set and see @deprecated annotations for input.

**Test Environment**:

- OS: MacOSX
- `@graphql-codegen/...`:
- NodeJS: 16

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Urigo** [comment]
@samchungy thank you for the contribution!
Can you maybe add a test to check the default behaviour change?

**Comment by charlypoly** [comment]
Hi @samchungy!

It is undocumented, but `inputValueDeprecation` (and all others `loadSchemaToolkit()`) can be directly override at the root of the config as follows:

```yaml
inputValueDeprecation: true
schema: ...
documents: ...
# ...
```

There is no need to update the package for this 🤓

**Comment by jereddanielson** [comment]
> Hi @samchungy!
> 
> It is undocumented, but `inputValueDeprecation` (and all others `loadSchemaToolkit()`) can be directly override at the root of the config as follows:
> 
> ```yaml
> inputValueDeprecation: true
> schema: ...
> documents: ...
> # ...
> ```
> 
> There is no need to update the package for this 🤓

This seems to work for the similar problem we were facing. Out of curiosity, why is this _undocumented_?

**Comment by kdawgwilk** [comment]
Is there a way to set this on just a single schema rather than at the root that applies to all?

**Comment by jannickj** [comment]
> Hi @samchungy!
> 
> It is undocumented, but `inputValueDeprecation` (and all others `loadSchemaToolkit()`) can be directly override at the root of the config as follows:
> 
> ```yaml
> inputValueDeprecation: true
> schema: ...
> documents: ...
> # ...
> ```
> 
> There is no need to update the package for this nerd_face

Could you expand on this example my config looks like:

```yaml
inputValueDeprecation: true
schema: http://localhost:3000/graphql
generates:
  out.g.cs:
    plugins:
      - dist/index.js
```

and when i run it I get:

```sh
npx graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate out.g.cs
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ out.g.cs
    Failed to load schema from http://localhost:3000/graphql:

    Unknown argument 'includeDeprecated' on field 'args' of type '[__Directive!]!'.

    
    GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
```

**Pull request closed without merging**
