### PR TITLE
Additional type argument to allow custom config.name for react-apollo HOCs

### PR DESCRIPTION
**Pull request by valerybugakov**
Fixes issue described in https://github.com/dotansimha/graphql-code-generator/issues/2192

### CODE REVIEW

**Comment by valerybugakov** [comment]
If somebody can suggest hot to reproduce CI issue locally I will be able to fix it. Strangely `yarn build-and-test` executes without errors locally:
Screenshot 2020-03-29 at 15 46 51

**Comment by ardatan** [comment]
As you can see in the example, CI takes `dev-test` diff so you need to run `yarn generate:examples` and commit :)

**Comment by valerybugakov** [comment]
@ardatan thanks for a quick response, committed examples 👍

**Comment by dotansimha** [comment]
Thank you @valerybugakov !

**Pull request merged**
