### PR TITLE
Resolvers for unions, interfaces and directives

### PR DESCRIPTION
**Pull request by kamilkisiela**
- [x] union
- [x] interface
- [x] directive for graphql-tools (old)
- [x] directive for graphql-tools (new) (there's no point of doing it, people can use *Args and Context)
- [x] scalar (no idea what we could generate here that would be helpful)

### CODE REVIEW

**Comment by dotansimha** [comment]
Scalars can just have an implementation of `GraphQLScalarType` for now

**Comment by kamilkisiela** [comment]
Yeah but how we can predict the type there? We can't tell if it's a string of number so what we can generate is a regular `GraphQLScalarType`, something that could be imported from `graphql`

**Comment by kamilkisiela** [comment]
Unions and Interfaces:

```graphql
```

```ts
export type TypeResolveFn<Types, Parent = {}, Context = {}> = (
  parent: Parent,
  context: Context,
  info: GraphQLResolveInfo
) => Maybe<Types>;

export namespace EntryResolvers {
  export interface Resolvers {
    __resolveType: ResolveType;
  }

  export type ResolveType<
    R = 'Post' | 'Comment',
    Parent = Post | Comment, 
    Context = {}
  > = TypeResolveFn<R, Parent, Context>;
}
```

Directives:

```graphql
directive @modify(limit: Int) on FIELD_DEFINITION
```

```ts
export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult, TArgs = {}, TContext = {}> = (
  next: NextResolverFn,
  source: any,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo,
) => TResult | Promise<TResult>;

export type ModifyDirectiveResolver<Result> = DirectiveResolverFn<Result, ModifyDirectiveArgs, {}>;

export interface ModifyDirectiveArgs {
  limit?: number | null;
}
```

**Comment by dotansimha** [comment]
Looks great!

**Pull request merged**
