### PR TITLE
Linting fixes

### PR DESCRIPTION
**Pull request by shmax**
## Description

Fixing some linting issues in generated output. See details in issue.

Related # (issue)
#8795 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

These are just linting fixes. I updated the relevant tests so that they pass.

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shmax** [comment]
Do any of you guyes develop in a Windows environment? I'm having trouble with the prettier script:

```sh
shmax@DESKTOP-N9F7C24 MINGW64 /d/repos/shmax/graphql-code-generator (linting-fixes)
$ yarn run prettier:check
yarn run v1.22.15
$ prettier --cache --check .
[error] Cannot find module 'node:path'
[error] Require stack:
[error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier-plugin-sh\lib\index.cjs
[error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\index.js
[error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\cli.js
[error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\bin-prettier.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is, of course, after running `yarn install`. Any ideas?

**Comment by saihaj** [comment]
> Do any of you guyes develop in a Windows environment? I'm having trouble with the prettier script:
> 
> ```shell
> shmax@DESKTOP-N9F7C24 MINGW64 /d/repos/shmax/graphql-code-generator (linting-fixes)
> $ yarn run prettier:check
> yarn run v1.22.15
> $ prettier --cache --check .
> [error] Cannot find module 'node:path'
> [error] Require stack:
> [error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier-plugin-sh\lib\index.cjs
> [error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\index.js
> [error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\cli.js
> [error] - D:\repos\shmax\graphql-code-generator\node_modules\prettier\bin-prettier.js
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> This is, of course, after running `yarn install`. Any ideas?

what node version?

**Comment by shmax** [comment]
> what node version?

14.16.0

**Review by B2o5T — APPROVED** [review]

**Comment by B2o5T** [comment]
> > what node version?
> 
> 14.16.0

you need to have at least `v14.18.0`

**Comment by shmax** [comment]
> you need to have at least v14.18.0

Okie-doke, I'll give it a try, thank you.

**Comment by B2o5T** [comment]
could you also add a changeset with `patch` version for modifying packages? so users will know about this improvement?

**Comment by shmax** [comment]
> could you also add a changeset with patch version for modifying packages? so users will know about this improvement in next release

Sure, if that's the custom.

**Comment by shmax** [comment]
I think I need a little help with changeset, too. I see it listed in package.json, but there is nothing under "scripts" for it, and when I try "yarn changeset" I get:

```
shmax@DESKTOP-N9F7C24 MINGW64 /d/repos/shmax/graphql-code-generator (linting-fixes)
$ yarn changeset
yarn run v1.22.15
$ D:\repos\shmax\graphql-code-generator\node_modules\.bin\changeset
/usr/bin/bash: D:reposshmaxgraphql-code-generatornode_modules.binchangeset: command not found
←[2K←[1G←[31merror←[39m Command failed with exit code 127.
←[2K←[1G←[94minfo←[39m Visit ←[1mhttps://yarnpkg.com/en/docs/cli/run←[22m for documentation about this command.
```

Same errors even after installing it globally. How does one use this tool?

**Comment by B2o5T** [comment]
> I think I need a little help with changeset, too. I see it listed in package.json, but there is nothing under "scripts" for it, and when I try "yarn changeset" I get:
> 
> ```
> shmax@DESKTOP-N9F7C24 MINGW64 /d/repos/shmax/graphql-code-generator (linting-fixes)
> $ yarn changeset
> yarn run v1.22.15
> $ D:\repos\shmax\graphql-code-generator\node_modules\.bin\changeset
> /usr/bin/bash: D:reposshmaxgraphql-code-generatornode_modules.binchangeset: command not found
> ←[2K←[1G←[31merror←[39m Command failed with exit code 127.
> ←[2K←[1G←[94minfo←[39m Visit ←[1mhttps://yarnpkg.com/en/docs/cli/run←[22m for documentation about this command.
> ```
> 
> Same errors even after installing it globally. How does one use this tool?

I've just added it for you, let's wait for another approve and we'll merge it

**Comment by shmax** [comment]
Sounds good, thanks much 👍

**Review by saihaj — APPROVED** [review]

**Comment by saihaj** [comment]
thanks @shmax!

**Comment by shmax** [comment]
Thanks for the review 👍

**Pull request merged**
