### PR TITLE
WIP: Refactor package

### PR DESCRIPTION
**Pull request by dotansimha**
Progress: 99.999%

The goals are: 
- [x] Move codegen core to a package and don't use `fs` 
- [x] Move generators to separate package
- [x] Refactor directories structure and use Lerna to manage package's dependencies 
- [x] Refactor GraphQL Schema template context builder and object
- [x] Handle fields and types in a better way  (related to https://github.com/dotansimha/graphql-code-generator/issues/96 and https://github.com/dotansimha/graphql-code-generator/issues/84) - my idea is to use expose the schema template context the same way GraphQL treat it's types (separate arrays for enum, type, input, union, interface, scalar)
- [x] Treat Query and Mutation just like any other type
- [x] Fix CI
- [x] Refactor operations builder with flatten feature
- [x] Reimplement `typescript-single-file`
- [x] Reimplement imports builder for multiple files 
- [x] Reimplement `typescript-multi-file`
- [x] Move and refactor CLI util to a separate package (use fs only here)
- [x] Add support for input/output of a whole project (to generate apps)
- [x]  Fix lerna dependencies 
- [x] Add support for magic comments to easier integration in existing project (`/*gqlgen {{#each types }} */`
- [x] Move generators to separate packages with compilation package 
- [x] Add support for directives (https://github.com/graphql/graphql-js/pull/746)
- [ ] Update README
 
After merging to master:
- [ ] Reimplement `flow-single-file`
- [ ] Reimplement `swift-single-file`
- [ ]  100% code coverage for core & compiler packages
- [ ] Blog post

Ideas:
- [x] Consider implementing the flatten types map in a better way - maybe just add a reference inside the template context to the actual type along the type name.

### CODE REVIEW

**Comment by dotansimha** [comment]
@DxCx  @zephraph any thoughts?

**Comment by zephraph** [comment]
Whew... this is a huge change. Okay, I'll comment as I can go through it...

**Comment by dotansimha** [comment]
@zephraph my goal is to simplify the schema handler first. 
I am almost done, and you can find it here: https://github.com/dotansimha/graphql-code-generator/blob/refactor/all/packages/graphql-codegen-core/src/schema/schema-to-template-context.ts
Also, I changed the schema template context object to be: https://github.com/dotansimha/graphql-code-generator/blob/refactor/all/packages/graphql-codegen-core/src/types.ts#L55-L62

This is much simpler implementation for the Schema handling, the difference is that I'm creating an array for each GraphQL base type (scalar/enum/type/input...), instead of a single array for all of them together. 

I also separated it to 3 packages: 
- core (GraphQLSchema and operations string => template context object)
- generators (combines template and template context, also in charge of converting primitives to language primitives, eg. `String` => `string` and `Int` to `number` in case of TS)
- cli (Find, read, introspect and execute generator + core)

**Comment by zephraph** [comment]
It might be a good idea to generate a copy of dev-test from master (on all supported variations) and have a test just for comparing final generated outputs.

**Comment by dotansimha** [comment]
@zephraph I'm done with the scheme generation for typescript, and it looks like the result file is the same as the current implementation - so we are good so far :)

**Comment by zephraph** [comment]
Cool! I'll run through the updates. There's a few things I want to test.

**Comment by dotansimha** [comment]
@zephraph do you have good use cases for complicated operations (fragment/mutation/query)? I want to use it to write tests before implementing.

**Comment by zephraph** [comment]
I don't at the moment but we can put one together.

**Comment by zephraph** [comment]
It's really starting to come together!

**Comment by dotansimha** [comment]
@zephraph almost there!! my next goal is to add the ability to generate a whole project with custom templates, something like this:
```
my-project/
    - index.js
    - router.js
    - graphql/
             - feed.graphql
    - wrappers/
              - operation.js.template
    - data-tables/
              - table.js.type.template
```

and you have a `type` called `MyType` on your GraphQLSchema.

The output will be:
```
    - index.js
    - router.js
    - graphql/
             - feed.graphql
    - wrappers/
              - operation.js.template
              - feed.query.js
    - data-tables/
              - table.js.type.template
              - mytype.table.js
```

This way, users can create a project and run the generator over a project's directory and generate anything they need that related to GraphQL (generate UI, HOC wrappers for React, ready-to-use `gql` wrappers or anything else :) )

What do you think?

**Pull request merged**
