### PR TITLE
Make variables optional if skip is provided

### PR DESCRIPTION
**Pull request by ardatan**
Related to https://github.com/dotansimha/graphql-code-generator/issues/1897

### CODE REVIEW

**Comment by cecchi** [comment]
Thanks! One thing: I think this disallows `skip` being `undefined` with `variables` being provided? We should treat `undefined` and `null` as equivalent to `false`.

**Comment by ardatan** [comment]
Good catch! :) Fixed

**Comment by benjie** [comment]
This also disables settings `skip` true when variables are supplied; could we instead have `skip?: boolean` when variables are supplied?

**Comment by boom** [comment]
This change currently breaks passing a variable to the `skip` property. See @benjie comment that 
```typescript
& ({ variables: FeedQueryVariables; skip?: false; } | { skip: true; });
``` 

should not reference boolean values but rather refer to the type `boolean`.

**Comment by boom** [comment]
Opened https://github.com/dotansimha/graphql-code-generator/pull/2251 to resolve.

**Pull request merged**
