### PR TITLE
Fix multiline comments

### LINKED ISSUE #950: Multiline comments are squashed without whitespace
**Describe the bug**
The following gql:

```gql
  # Decides the order a module will run in. Modules with the same
  # level, will run in parallel.
  level: Int!
```

turns into this in typescript

```ts
  /** Decides the order a module will run in. Modules with the samelevel, will run in parallel. */
  level: number;
```

Notice that `same` and `level` get's merged to `samelevel`.

**Expected behavior**

I expected the comment to either be multiline, or be

```ts
/** Decides the order a module will run in. Modules with the same level, will run in parallel. */
```

**Environment:**
 - OS: OSX
 - Codegen: v0.14.4
 - Node: v11.2.0

**Additional context**
I've looked into the code a bit, and in all likelihood, changing `oneLineTrim` to `oneLine` will fix this issue:

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/utils/plugins-handlebars-helpers/src/index.ts#L2

### PR DESCRIPTION
**Pull request by Alxandr**
Resolves #950

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@Alxandr Thank you very much! 
Could you add a unit test for that or give me an access to make changes (there'a checkbox on the right)?

**Comment by Alxandr** [comment]
Checkbox is already checked. Also, I figured splitting up one of the existing comments and having it still pass the tests would cover the change?

**Comment by kamilkisiela** [comment]
Yeah, you can copy paste some test and change the description, just so we can tell what's the purpose of it.

**Comment by dotansimha** [comment]
Thanks @Alxandr ! Merged :)

**Pull request merged**
