### PR TITLE
Bump GraphQL Tools for Schema Sorting and the fix for the schema definition handling

### PR DESCRIPTION
**Pull request by DronBrigadir**
## Description

Use graphql.lexicographicSortSchema in transformSchemaAST depending on the parameter - sort
Bumps GraphQL Tools package that handles schema definitions correctly

Related #6624 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

**Test Environment**:
- OS: macOS Catalina version: 0.15.7
- `@graphql-codegen/typescript`: "2.2.0"

### CODE REVIEW

**Comment by ardatan** [comment]
Thanks!
Could you add some unit tests to prevent future regressions?

**Comment by Sytten** [comment]
I think this might the cause of the changes I saw in my output. Example
```
export type Balance = {
  __typename?: 'Balance';
- payouts: Array<Payout>;
  liabilities: Array<Liability>;
+ payouts: Array<Payout>;
  total: Scalars['Int'];
};
```
I did not enable sorting so I feel this is a regression @ardatan @DronBrigadir

**Comment by ardatan** [comment]
It is not a regression. It is a fix actually. Sorting is enabled by default by codegen but schema wasn't properly sorted so this was causing an inconsistency in output. You can do "sort: false".

**Comment by Sytten** [comment]
Yeah had the discussion on slack, my bad.

**Pull request merged**
