### PR TITLE
feat: migrate to listr2

### PR DESCRIPTION
**Pull request by saihaj**
See changeset

### CODE REVIEW

**Review by n1ru4l — APPROVED** [review]

**Review by ardatan — APPROVED** [review]

**Review by kamilkisiela — APPROVED** [review]

**Review by dotansimha — APPROVED** [review]
Rebase and then we are good to go. Thanks @saihaj

**Comment by saihaj** [comment]
future task to figure out https://github.com/dotansimha/graphql-code-generator/issues/8045

**Comment by vhenzl** [comment]
This change seems to make the `config.errorsOnly` option (and the `--errors-only` CLI flag) unused.

**Comment by charlypoly** [comment]
> This change seems to make the `config.errorsOnly` option (and the `--errors-only` CLI flag) unused.

@vhenzl, you are right, is there an option that you were actively using?

**Comment by vhenzl** [comment]
> > This change seems to make the `config.errorsOnly` option (and the `--errors-only` CLI flag) unused.
> 
> @vhenzl, you are right, is it an option that you were actively using?

Nah, I just discovered it when debugging #8382.

**Comment by marco2216** [comment]
We are very much missing the --errors-only option. Was it removed on purpose?
Recent issue here https://github.com/dotansimha/graphql-code-generator/issues/8477

**Comment by adamperrry** [comment]
Any chance we could get the `errorsOnly` config option to work again? Watch mode output is really spamming our build script.

**Pull request merged**
