### PR TITLE
Allow to override apollo-angular package

### PR DESCRIPTION
**Pull request by dotansimha**
Related: https://github.com/dotansimha/graphql-code-generator/issues/3944

### CODE REVIEW

**Comment by cjohn001** [comment]
Hello Dotan,
thanks for the quick support! I updated my packages with 

npx match-version @graphql-codegen 1.13.5-alpha-7b00b74c.0+7b00b74c

and use the following programmatic configuration:

		const codegenSettings = {
			schema: {
				[baseUrlGraphQLSchema]: {
					headers: {
						Authorization: `Bearer ${token}`
					}
				}
			},
			documents: process.cwd() + '/src/app/shared/graphql/**/*.graphql',
			generates: {
				[process.cwd() + '/src/app/shared/graphql/graphql.ts']: {
					plugins: [
						'typescript',
						'typescript-operations',
						{
							'typescript-apollo-angular': {
								apolloAngularPackage: 'offix-angular'
							}
						},
						'fragment-matcher'
					]
				},
				[process.cwd() + '/src/app/shared/graphql/fragmentTypes.json']: {
					plugins: ['fragment-matcher']
				}
			}
		};
		// generate typescript types
		await generate(codegenSettings, true);

but unfortunately it does not work. In the generated file output I still have 

import * as Apollo from 'apollo-angular';

Is my programmatic configuration correct?

Best regards,
 Christoph

**Comment by dotansimha** [comment]
This should work... can you please try to move the config to higher hierarchy and check again? 
Also, please make sure that all codegen related packages are using the same version, and you don't have `^` or `~` in the version. 

 @cjohn001

**Comment by cjohn001** [comment]
@dotansimha 

I switched the config to the following now:
		const codegenSettings = {
			schema: {
				[baseUrlGraphQLSchema]: {
					headers: {
						Authorization: `Bearer ${token}`
					}
				}
			},
			documents: process.cwd() + '/src/app/shared/graphql/**/*.graphql',
			generates: {
				[process.cwd() + '/src/app/shared/graphql/graphql.ts']: {
					plugins: ['typescript', 'typescript-operations', 'typescript-apollo-angular', 'fragment-matcher'],
					apolloAngularPackage: 'offix-angular'
				},
				[process.cwd() + '/src/app/shared/graphql/fragmentTypes.json']: {
					plugins: ['fragment-matcher']
				}
			}
		};

But this unfortunately does not help. In my package.json I have the following:

    "@graphql-codegen/cli": "1.13.5-alpha-7b00b74c.0+7b00b74c",
    "@graphql-codegen/fragment-matcher": "1.13.5-alpha-7b00b74c.0+7b00b74c",
    "@graphql-codegen/introspection": "1.13.5-alpha-7b00b74c.0+7b00b74c",
    "@graphql-codegen/typescript": "1.13.5-alpha-7b00b74c.0+7b00b74c",
    "@graphql-codegen/typescript-apollo-angular": "1.13.5-alpha-7b00b74c.0+7b00b74c",
    "@graphql-codegen/typescript-operations": "1.13.5-alpha-7b00b74c.0+7b00b74c",

I am not 100% sure if I understood you correctly with
>> can you please try to move the config to higher hierarchy and check again?
Is the config I now used as you intended? If not please give an example.

**Comment by dotansimha** [comment]
@cjohn001 this works?

```js
		const codegenSettings = {
			schema: {
				[baseUrlGraphQLSchema]: {
					headers: {
						Authorization: `Bearer ${token}`
					}
				}
			},
			documents: process.cwd() + '/src/app/shared/graphql/**/*.graphql',
			generates: {
				[process.cwd() + '/src/app/shared/graphql/graphql.ts']: {
					plugins: ['typescript', 'typescript-operations', 'typescript-apollo-angular', 'fragment-matcher'],
					config: {
                      apolloAngularPackage: 'offix-angular'
                    }
				},
				[process.cwd() + '/src/app/shared/graphql/fragmentTypes.json']: {
					plugins: ['fragment-matcher']
				}
			}
		};
```

**Comment by dotansimha** [comment]
Oh I see :) So that makes sense to use the programmatic api. 
We can keep the issue open until we'll release a stable version.

**Comment by cjohn001** [comment]
Ok, great. Thanks once again!

**Pull request merged**
