### PR TITLE
feat: add typesSuffix option to Flow plugin (fixes #4522)

### LINKED ISSUE #4522: Add a way to suffix all Flow generated types
**Is your feature request related to a problem? Please describe.**

Feature request.

**Describe the solution you'd like**

I would like to specify a common prefix for all generated types.

**Describe alternatives you've considered**

N/A

**Additional context**

The current generated types appear as literal names in GraphQL schema, e.g.

```js
export type AuthenticateInput = {|
  authenticationToken: $ElementType<Scalars, 'String'>,
  email: $ElementType<Scalars, 'String'>,
|};

```

Our coding guidelines require that all types are suffixed with "Type", i.e. the expected output is:

```js
export type AuthenticateInputType = {|
  authenticationToken: $ElementType<Scalars, 'String'>,
  email: $ElementType<Scalars, 'String'>,
|};

```

It would be nice to be able to add that suffix.

### PR DESCRIPTION
**Pull request by gajus**

### CODE REVIEW

**Comment by gajus** [comment]
Technically this also makes the option available to other plugins, but I have only updated Flow documentation as it is not clear how the changes for other plugins are handled.

**Comment by gajus** [comment]
@dotansimha it is not clear why the CI is failing.

**Comment by dotansimha** [comment]
Thank you @gajus ! I'm not sure regarding `appendArgsSuffix` because it feels like a very specific flag, that might no be relevant to all naming conversions.

**Comment by gajus** [comment]
> Thank you @gajus ! I'm not sure regarding `appendArgsSuffix` because it feels like a very specific flag, that might no be relevant to all naming conversions. Maybe let's try to keep it simple and just add the `typesSuffix`, and we can try to improve the hardcoded `Args` in a future PR?

Done.

**Comment by dotansimha** [comment]
This is perfect. Thank you @gajus !

**Pull request merged**
