### PR TITLE
feat(plugin: graphql-requests): Support the request header parameter …

### PR DESCRIPTION
**Pull request by moeHaydar**
A new feature is being supported by graphql-request library: Support passing custom headers per each request method.
This PR is to support the extra parameter than can be passed to the generated code in the plugin.

graphql-request: PR: prisma-labs/graphql-request#228

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @moeHaydar ! Let's wait until it's available in `graphql-request` and then we can merge it here as well.

**Comment by moeHaydar** [comment]
@dotansimha PR merged there :) we are all good to merge here.

**Comment by dotansimha** [comment]
Great, thanks! Waiting for a release. Is it a breaking change? in terms of users who are using previous versions of this library? (I mean old graphql-request and the changes for this PR)

**Comment by dotansimha** [comment]
Just an update: It's still in `next` version (`3.4.0-next.1`) and not in a stable release, so this PR is still pending.

**Comment by dotansimha** [comment]
Ok so `3.4.0` is out. We can get this merged :)

**Pull request merged**
