### PR TITLE
[typescript] Added `disableComments` to remove ignore all descriptions

### PR DESCRIPTION
**Pull request by TheOnlyBeardedBeast**
Extended typescript generation, added `disableComments` option

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @TheOnlyBeardedBeast ! 
I think we might be able to implement this with minimal changes. 
One of the advantages of AST visiting is the ability to modify the AST and transform it. So I think removing comments can be done on a simpler form, with less code changes.


```ts
import { parse, visit } from "graphql";

const exampleAst = parse(`type Query { """this is a commit""" test: String }`);
const withoutComments = visit(exampleAst, { 
  leave: {
    FieldDefinition: node => ({ ...node, description: null }),
    ObjectTypeDefinition: node => ({ ...node, description: null }),
    // ... 
  }
});
```

What do you think?

**Comment by TheOnlyBeardedBeast** [comment]
I like it, it would be easier to implement and maybe reusable for other plugins this way, I will take a look at it. @dotansimha

**Comment by dotansimha** [comment]
@TheOnlyBeardedBeast that's great! Let me know what it's ready for review ;) Thanks!

**Comment by dotansimha** [comment]
@TheOnlyBeardedBeast update? :)

**Comment by TheOnlyBeardedBeast** [comment]
@dotansimha Hi, sorry for the late work, I had some business trips etc. I created an transformSchemaAST, I let the config abstract, if multiple transforms would be needed in the future. This function allows to transform the schema and the AST and return their transformed version.
```typescript
transformSchemaAST(schema: GraphQLSchema, config: { [key: string]: any })
```
Also the config flag was changed as requested.

**Comment by TheOnlyBeardedBeast** [comment]
@dotansimha any news? Do you require any changes?

**Comment by ardatan** [comment]
Thank you very much! Sorry it took so long to merge that :)

**Comment by TheOnlyBeardedBeast** [comment]
@ardatan Sure, no problem, I understand, maintaining a project takes time. I am happy that it was merged 🙂

**Pull request merged**
