### PR TITLE
regression fix: options should be typed as optional

### PR DESCRIPTION
**Pull request by JoeSchr**
fix for #5053

### CODE REVIEW

**Comment by dotansimha** [comment]
@JoeSchr any news on this one? :) thanks!

**Comment by JoeSchr** [comment]
Sorry, totally forgot about this. Will see what I can do after Xmas stuff is over

**Comment by ardatan** [comment]
@JoeSchr Thanks for the PR! Is it ready to merge?

**Comment by JoeSchr** [comment]
> @JoeSchr Thanks for the PR! Is it ready to merge?

Sadly no. feature is working but I haven't had time to adapt all the fixture test data which compares it with the generated graphql. Because with this kind of PR that is now changed ofc.

If anybody want to jump in, be my guest, otherwise I currently can't make any promises when I can come around to this.

**Comment by dotansimha** [comment]
> > @JoeSchr Thanks for the PR! Is it ready to merge?
> 
> Sadly no. feature is working but I haven't had time to adapt all the fixture test data which compares it with the generated graphql. Because with this kind of PR that is now changed ofc.
> 
> If anybody want to jump in, be my guest, otherwise I currently can't make any promises when I can come around to this.
> @ardatan

Thanks @JoeSchr . Closing for now, feel free to reopen if you have time to work on it again.

**Pull request closed without merging**
