### PR TITLE
fix(cli): properly resolve template plugins on all platforms

### PR DESCRIPTION
**Pull request by Diizzayy**
This PR uses `pathToFileURL` to use the `file://` url scheme to resolve plugins. Current behavior in `@graphql-codegen/cli` causes a crash when ran on windows.

Related #7664 Diizzayy/nuxt-graphql-client#15

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gkkirilov** [comment]
Doesn't pass some unit tests

**Comment by charlypoly** [comment]
@Diizzayy, could you rebase your PR and test it again on Windows? 🙏🏼 🙏🏼 Thanks!

**Comment by Diizzayy** [comment]
@charlypoly Sure thing, I'll hop on it right away.

**Comment by charlypoly** [comment]
> @charlypoly Sure thing, I'll hop on it right away.

@Diizzayy thank you!

**Comment by charlypoly** [comment]
> @charlypoly Sure thing, I'll hop on it right away.

Hi @Diizzayy,

could you rebase your PR and test it on Windows?
Then, we'll be good to merge.

**Comment by Diizzayy** [comment]
@charlypoly Thank you, I'll rebase and have a look at it.

Also, Do you happen to have discord? We're having some issues over at [Nuxt](https://github.com/nuxt/framework) with recent changes to the graphql-codegen cli. I would love to be able to discuss with you a bit on the topic so we can come to a suitable solution for the nuxt modules which integrate GraphQL client support leveraging the tools you guys provide.

**Comment by Diizzayy** [comment]
@charlypoly I've had the chance to look at this again, and it seems that the esm issues on windows were previously addressed in #7978

**Pull request closed without merging**
