### PR TITLE
Feat/configurable composition api import

### PR DESCRIPTION
**Pull request by iskanderbroere**
adds a config option to change the package the vue composition api is imported from.

Related to https://github.com/dotansimha/graphql-code-generator/issues/4703

### CODE REVIEW

**Comment by iskanderbroere** [comment]
@ardatan can you take a look at this one?

**Comment by dotansimha** [comment]
@iskanderbroere Thank you, that's great.
Can you please add changeset for that change? (run `yarn changeset`, it will guide you)
I think we need a minor bump here .

**Comment by iskanderbroere** [comment]
alright i updated the PR

**Comment by dotansimha** [comment]
Thank you @iskanderbroere !

**Pull request merged**
