### PR TITLE
Add first boilerplate setup for webpack loader

### PR DESCRIPTION
**Pull request by mxstbr**
Reference #1828, this solely does the first setup for the package and nothing else.

@dotansimha how are we going to run the raw file contents through the graphql-codegen plugins?

### CODE REVIEW

**Comment by dotansimha** [comment]
That's awesome! Thank you @mxstbr ! 

A few thoughts:
- I think maybe we can create a separate package for that, that compiles `.graphql` files into a ready-to-use HOC/Component/Hooks, and allow it to be pure JavaScript.
- Then, we can create a codegen plugin that supports this package by generating typings for it (using `declare module`). This way the package could be used as pure JS without the codegen, and the codegen can support it with typings (we can do it for both Flow an TS).

**Comment by mxstbr** [comment]
That sounds like a great plan to me! I'm not well versed enough in the codebase to tackle that, so I'll leave it up to you :pray:

**Comment by eddeee888** [comment]
Hello! Just wondering what's the state of this? Would love to help to push this forward

> Then, we can create a codegen plugin that supports this package by generating typings for it (using declare module). This way the package could be used as pure JS without the codegen, and the codegen can support it with typings

Is this similar to `typescript-react-apollo` plugin? If I understand this correctly, we create declaration files `d.ts` instead of `.tsx` files?

**Comment by mxstbr** [comment]
I have not enough expertise in the graphql-codegen codebase to pick this up further, I would love for somebody else to pick this up and implement the functionality!

**Comment by dotansimha** [comment]
So now we are able to load document from the original source file, thanks to @eddeee888 . I think it's one step forward in order to get easy integration with Webpack.

**Comment by CarloPalinckx** [comment]
If we could skip outputting implementation and limit the loader to just output declaration files matching the .graphql modules we could solve a lot of confusion that has led to the "near-operation-file" preset. Because all a user would be doing is import the .graphql file 🤩:

In a `globals.d.ts` file:

```
declare module '*getProducts.graphql' {
// generated types
}
```

in a `Products` component: 
```
import useGetProductsQuery from 'getProducts.graphql';

...
const { data, loading, error } = useGetProductsQuery();
...
```

A tradeoff to this aproach is that we would probably needs some in memory caching to keep it quick.

**Comment by eddeee888** [comment]
Hello! I have made a small repo to see if this is doable ( also to play with webpack loader since I have never done it before! )

https://github.com/eddeee888/experiment-apollo-hooks-loader

And here's [the loader](https://github.com/eddeee888/experiment-apollo-hooks-loader/blob/master/loaders/src/apollo-hooks-loader.ts)

If this is in the right direction, I can try to bring it over and iterate on it?

**Comment by dotansimha** [comment]
WOW @eddeee888 ! 
This is awesome!!! I'll try it locally later this week.

**Comment by GiancarlosIO** [comment]
:eyes:

**Comment by dotansimha** [comment]
Let's continue the discussion here: https://github.com/dotansimha/graphql-code-generator/issues/3494 
Thank you :)

**Pull request closed without merging**
