### PR TITLE
ci: install rust wasm target first before building

### PR DESCRIPTION
**Pull request by YassinEldeeb**

### CODE REVIEW

**Review by n1ru4l — CHANGES_REQUESTED** [review]
please rename the package to `@graphql-codegen/client-preset-swc`

**Comment by YassinEldeeb** [comment]
> please rename the package to @graphql-codegen/client-preset-swc

@n1ru4l I pushed it before you mentioned it 😛

image

**Review by n1ru4l — APPROVED** [review]

**Comment by YassinEldeeb** [comment]
@saihaj what's this?
image
image

**Comment by saihaj** [comment]
@YassinEldeeb unsure we can ignore for now and investigate it later

**Pull request merged**
