### PR TITLE
fix(vue-apollo): keep up with @vue/apollo-composable

### PR DESCRIPTION
**Pull request by aki77**
keep up with vuejs/vue-apollo@81475da

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @aki77  :) Is that a breaking change in vue-apollo? Do we need to notify users that this change only supported from a specific version of vue-apollo?

**Comment by aki77** [comment]
Thanks @dotansimha !

This is not a breaking change for users using vue-apollo alone.
But for users using @graphql-codegen/typescript-vue-apollo, this is a breaking change.
So I think we should notify them that @vue/apollo-composable@^4.0.0-alpha.12 is the target.

**Comment by dotansimha** [comment]
Got it. I wonder if this needs to be merge right now, since `@vue/apollo-composable` is still alpha, and I don't think it's a good idea to bump major version for a codegen plugin, based on an alpha API that might change later.

**Comment by aki77** [comment]
I'm fine with minor upgrades.
Because as a codegen plugin it doesn't introduce any breaking changes to the API.
To begin with, only the alpha version of @vue/apollo-composable exists.
The best option is to keep up with the latest version of @vue/apollo-composable.

**Comment by nickreynke** [comment]
Good work. Would love to see this merged anytime soon.

I tried to work with Vue3 in combination with Apollo Client and AWS AppSync but got into trouble setting it up using the generated types from codegen.

**Comment by quentinus95** [comment]
This would unlock the possibility to upgrade existing Vue apps that are using this codegen lib to Apollo Client 3. I think it's worth merging and releasing this ASAP.

**Comment by P4sca1** [comment]
There is another PR which fixes this bug along with other improvements and fixes to the vue apollo plugin: https://github.com/dotansimha/graphql-code-generator/pull/5007

**Comment by aki77** [comment]
@P4sca1 Good work!

@dotansimha I think the PR for #5007 should be merged.

**Comment by dotansimha** [comment]
Great, thank you all for your amazing contributions. We'll get https://github.com/dotansimha/graphql-code-generator/pull/5007 merged now :)

**Pull request closed without merging**
