### PR TITLE
test(typescript-react-apollo): Implement fix for #6001

### PR DESCRIPTION
**Pull request by ImLuze**
## Description

Implement a fix for #6001, `typescript-react-apollo` should use `typesSuffix` on type names but not on operation names.

Related #6001 

## Type of change

- [x] Breaking change: The generated output would be slightly changed after this issue is fixed.

## How Has This Been Tested?

- [x] A failing automated test has been added for `typescript-react-apollo`.
- [x] Tested manually on an existing project. 

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Urigo** [comment]
Thank you so much @ImLuze !

This clearly demonstrate the issue and helps us a lot.

If you are up for trying to solve it, we would be very grateful!
If you have any questions or need help while you are trying, feel free to contact us directly.
Also you can check the video tutorials on our [contribution docs](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md)

**Comment by ImLuze** [comment]
I'll gladly take a look at this one. Although it might take me a couple weeks to do so if that's ok. Life is quite busy right now.

**Comment by ImLuze** [comment]
@Urigo Hi, just letting you know that I managed to find a fix for this. If you need anything else from me. Please let me know 😉

**Comment by dotansimha** [comment]
Thank you so much @ImLuze !

**Pull request merged**
