### PR TITLE
[typescript-vue] Update composition api changes

### PR DESCRIPTION
**Pull request by angad777**
createComponent has been changed to defineComponent

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @angad777 ! 
Can you please explain what versions of Vue has changed? because this seems like a breaking change, so I would like to consider to bump `major` version for that plugin release.

**Comment by angad777** [comment]
> Thank you @angad777 !
> Can you please explain what versions of Vue has changed? because this seems like a breaking change, so I would like to consider to bump `major` version for that plugin release.

Welcome mate @dotansimha 

The change for `createComponent` to `defineComponent` was introduced in version `@vue/composition-api": "^0.5.0"`

FYI : this is only if people have opted in to using the new vue composition api.

Thanks

**Comment by dotansimha** [comment]
I see, so we need a major bump. Can you please create a changeset that matches it? (run `yarn changeset` and it will guide you through the rest of the flow)

**Comment by angad777** [comment]
> I see, so we need a major bump. Can you please create a changeset that matches it? (run `yarn changeset` and it will guide you through the rest of the flow)

Sure, no worries mate. I've added changeset. Thanks

**Comment by dotansimha** [comment]
Thank you @angad777 !

**Pull request merged**
