### PR TITLE
Implement additional configuration for C# plugin related to JSON attributes, remove redundant dependency on `GraphQL` namespace

### PR DESCRIPTION
**Pull request by seclerp**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The test was made using different sample schemas added to `dev-test/codegen.yml` with different arguments given to the plugin.

**Test Environment**:
- OS: Windows
- `@graphql-codegen/cli` (locally built)
- `@graphql-codegen/c-sharp` (locally built)
- NodeJS: 14.16.1

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

Related #6340
Related #6341

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]
This looks nice, thank you @seclerp ! 
I see that the PR is still marked as draft, is there anything else missing before we can merge this?

**Comment by seclerp** [comment]
@dotansimha thanks, I am stuck in manual testing this pkugin as a local package, as it a requirement for PR

**Comment by seclerp** [comment]
I spent a lot of time trying to build plugin, it is a not chabges related issue :)

**Comment by seclerp** [comment]
> > @dotansimha thanks, I am stuck in manual testing this plugin as a local package, as it is a requirement for PR
> 
> You can use `yarn build` to build all packages locally,  and then you can use `dev-test` to create a local output. Take a look at `dev-test/codegen.yml`, we have a very long list of test outputs.
> 
> Also, if you want to test it locally in an external project, you can use `npm pack` in the project root, and then refer to the compressed `tgz` in a `package.json`. 

Thank you, will check it out and after testing will ping you

**Comment by seclerp** [comment]
@dotansimha sorry for being late with that, I'm done with testing, PR could be merged

**Comment by seclerp** [comment]
@dotansimha did you had a chance to look into it? 😃

**Comment by dotansimha** [comment]
Thanks @seclerp ! Sorry for the delay! :)

**Pull request merged**
