### PR TITLE
Use importFrom to import external fragments

### PR DESCRIPTION
**Pull request by mjbcopland**
Discussion on #3525

Would be good to get @micimize's thoughts on what that TODO was for and whether this is a reasonable change.

### CODE REVIEW

**Comment by micimize** [comment]
It was about whether to replace it with a generated import statement per-fragment, but I think it was made irrelevant by the `generateImportStatement` used for `fragmentImportStatements`.

**Comment by dotansimha** [comment]
It seems like we should have a different solution, as you suggested. 
The changes I did there yesterday was just a workaround, and I think plugins should be in charge of adding those imports. This way the import for `FragmentDoc` will be done by `ClientSideBaseVisitor` and not by the preset itself (but, the preset should let the plugin know where the fragment file is located).

**Comment by wassim-k** [comment]
@dotansimha what's the status of this PR?

I'm working on a 3rd party plugin which requires fragment doc imports, unfortunately the current implementation does not work, since `DOC_VAR_PLUGINS` array cannot know about 3rd party plugins.

If you can let me know what's missing from this PR? I can attempt a different solution if you don't think this one solves the problem?

**Comment by wassim-k** [comment]
I've created a PR #3771 for an improved implementation, looking forward to your feedback.

**Comment by dotansimha** [comment]
Merged https://github.com/dotansimha/graphql-code-generator/pull/3771 recently, with improved implementation, so we can close this one. 

Thank you @mjbcopland , @micimize , @wassim-k for amazing work!

**Pull request closed without merging**
