### PR TITLE
Add field wrapper for list type item [plugins/typescript]

### PR DESCRIPTION
**Pull request by alex-knyazev**
Related to issue:  https://github.com/dotansimha/graphql-code-generator/issues/3882

Add wrapping in field wrapper in list item element

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @alex-knyazev ! 
I think these changes are good, but it seems like it handles `string` a bit too much. I think maybe we can improve that and solve that before having this `Maybe...` string that we need to process.

**Comment by alex-knyazev** [comment]
> Thank you @alex-knyazev !
> I think these changes are good, but it seems like it handles `string` a bit too much. I think maybe we can improve that and solve that before having this `Maybe...` string that we need to process.

**Comment by alex-knyazev** [comment]
> Thank you @alex-knyazev !
> I think these changes are good, but it seems like it handles `string` a bit too much. I think maybe we can improve that and solve that before having this `Maybe...` string that we need to process.

I tried to do it more beautiful , but I always added this logic to inputs. Can you suggest where to see?

**Comment by dotansimha** [comment]
@alex-knyazev I think this should be moved into `base-types-visitor.ts` and then it will be more compatible. I'm trying to move it there, into `FieldDefinition` or `NamedType` visitor functions, and see if it works. I'll update very soon ;)

**Comment by dotansimha** [comment]
Thank you @alex-knyazev :) I used your tests and applied a fix for it here: https://github.com/dotansimha/graphql-code-generator/pull/3938

BTW, I'm pretty sure that we need to use `Maybe<Wrapper<Type>>` and not `Wrapper<Maybe<Type>>`, what do you think?

**Comment by alex-knyazev** [comment]
> Thank you @alex-knyazev :) I used your tests and applied a fix for it here: #3938
> 
> BTW, I'm pretty sure that we need to use `Maybe<Wrapper<Type>>` and not `Wrapper<Maybe<Type>>`, what do you think?

I think yes, you right

**Pull request closed without merging**
