### PR TITLE
Umbrella PR - federation resolvers plugin refactor

### PR DESCRIPTION
**Pull request by kamilkisiela**
Yes we already support Federation in `typescript-resolvers` but it kind of broken... and we want to fix it!

## Umbrella PR

Treat this PR as a base for smaller, atomic PRs. Here's a [doc on Notion](https://www.notion.so/Federation-typescript-resolvers-3b47e825ff9a43b7a970c28e8784a6f70) explaining what, how and why.

## We need help!

We want to get there quickly and if there's a chance someone from the community can help us, it would be awesome! 😎 

A list of tasks is available as jest tests (or todos) in `packages/plugins/typescript/resolvers/tests/federation.spec.ts` file but also here:

- [x] should add `__resolveReference` to objects with `@key`
- [x] `__resolveReference` should use a union of `@key` directives
- [ ] only fields specified by `@requires` should be available in parent object
- [x] do not create resolvers for `@external` fields
- [ ] should accept a `reference`
- [ ] should accept a `reference` based on union of `@key` directives
- [x] should NOT accept a `reference` on an external type without `@key`
- [x] should NOT accept a `reference` on an external type (with `@extends`) without `@key`
- [x] should NOT accept a `reference` on a local (non-external) type
- [ ] support `__resolveObject`
- [ ] should mapper apply to `__resolveReference` as output?
- [ ] should mapper apply to `__resolveReference` as input?
- [ ] mappers should not collide with references - both accepted
- [ ] check if Federation allows to resolve a custom object and if so then what data goes to other services - is it the custom object or an object matching GraphQL type.

## How to help

You can help in two ways:
- create a test to make sure we follow federation spec
- implement a part of Federation into typescript-resolvers plugin
- discuss with us the implementation and tests
- make sure we follow Federation spec

if you eager to help, please mention @kamilkisiela (me) or @dotansimha in a comment and let's get things done!

### CODE REVIEW

**Comment by skk2142** [comment]
Hi @kamilkisiela thanks for working on this! In the todo list, `do not create resolvers for @external fields` is not necessarily correct. The resolver for that field is called. It becomes necessary to resolver that field when I have a mapper. For instance, in the schema below, if I have a custom mapper for `User`, say `{ userId: string }` and I am resolving the `reviewer` field, I will return `{ userId: "some-id"}` from the resolver function for `reviewer`. To resolve the correct federation entity for `User`, I need to return the `id` field of `User` even though it is an external field. Does that sound correct?

```graphql
extend type User @key(fields: "id") {
  id: ID @external
}
type Review {
  id: ID!
  reviewer: User
}
type Query {
   review(id: ID!): Review
}
```

**Comment by skk2142** [comment]
Also, I've been doing some experiment with federation. I think the `__resolveReference` method should return the mapper for the entity. The parent object of the `__resolveReference` resolver should be an object with fields specified in `fields` of the entity's key.

**Comment by skk2142** [comment]
Hi @kamilkisiela We are a heavy user of apollo federation and we are encountering many issues with this library for typescript. I'd love to talk about how we can help to expedite apollo federation support.

**Comment by dotansimha** [comment]
> Hi @kamilkisiela We are a heavy user of apollo federation and we are encountering many issues with this library for typescript. I'd love to talk about how we can help to expedite apollo federation support.

Hi! We would love to start a discussion about that. I think this PR is the ideal place for that :)

**Comment by Urigo** [comment]
Hi @skk2142, we would still love your help and feedback.
Would you like to start the discussion here?
If you want, we are also open to schedule a call

**Comment by skk2142** [comment]
HI @Urigo would love to explain the issues. Call would be easier and after that may be I can add more details as needed.

**Comment by charlypoly** [comment]
Putting this PR aside and will come back later to this concern.

**Pull request closed without merging**
