### PR TITLE
fix(visitor-plugin-common): union/interface types with same selection set field name but different type (#2436)

### LINKED ISSUE #2436: incorrect types on fragments
we're getting incorrect types on some generated types, see below. I commented on the final snippet in the generated code where the types are seemingly wrong

```
type DashboardTileChartDetails {
  tileId: String!
  wsId: UUID!
  chartId: String!
  md: TileChartMetadata # null if we error out
}

type TileChartMetadata {
  connection: Connection!
  viz: JsonBlob!
  columnInfo: JsonBlob! # the ColumnInfo type;
}

type DashboardTileFilterDetails {
  tileId: String!
  md: TileFilterMetadata
}
```

```
const DashboardVersionFragment = gql`
  fragment DashboardVersionFragment on DashboardVersion {
    ...DocumentVersionFragment
    tiles {
      ... on DashboardTileChartDetails {
        tileId
        wsId
        chartId
        md {
          viz
          columnInfo
          connection {
            ...ConnectionFragment
          }
        }
      }
      ... on DashboardTileFilterDetails {
        tileId
        md {
          columnType
          connection {
            ...ConnectionFragment
          }
        }
      }
      ... on DashboardTileParameterDetails {
        tileId
        md {
          parameterConstraint
          parameterLabel
        }
      }
    }
  }
  ${DocumentVersionFragment}
  ${ConnectionFragment}
`;
```

```
export type DashboardVersionFragmentFragment = (
  { __typename?: 'DashboardVersion' }
  & { tiles: Array<(
    { __typename?: 'DashboardTileChartDetails' }
    & Pick<DashboardTileChartDetails, 'tileId' | 'wsId' | 'chartId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'viz' | 'columnInfo'>
      & { connection: { __typename?: 'Connection' }
        & ConnectionFragmentFragment
       }
    )> }
  ) | (
    { __typename?: 'DashboardTileFilterDetails' }
    & Pick<DashboardTileFilterDetails, 'tileId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'columnType'> // should pick TileFilterMetadata
      & { connection: { __typename?: 'Connection' }
        & ConnectionFragmentFragment
       }
    )> }
  ) | { __typename?: 'DashboardTileTextDetails' } | (
    { __typename?: 'DashboardTileParameterDetails' }
    & Pick<DashboardTileParameterDetails, 'tileId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'parameterConstraint' | 'parameterLabel'> // should pick TileParameterMetadata
    )> }
  )> }
)
  & DocumentVersionFragmentFragment
;
;
```

### PR DESCRIPTION
**Pull request by n1ru4l**
Fixes #2436

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @n1ru4l !

**Comment by tanguyantoine** [comment]
Cool

**Comment by tanguyantoine** [comment]
any idea when you'll release this fix?

**Comment by dotansimha** [comment]
It's available in 1.7.0 :)

**Pull request merged**
