### PR TITLE
GraphQL Code Generator v3: RFC umbrella PR

### PR DESCRIPTION
**Pull request by charlypoly**
- [x]  **Remove `augmentedModuleName`  and expose a `graphql()` instead of `gql()`**
    - [x]  update preset generation code
    - [x]  ensure `graphql-tools` loaders can identify those `graphql()` calls
    - [x]  rename babel-plugin → babel-optimizer-plugin
- [x]  stop forwarding `plugins` (config) to `typescript` and `typescript-operations` plugin
- [x]  Target codegen config design

```ts
const config = {
  schema: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
  documents: ['src/**/*.tsx'],
  generates: {
    './src/gql/': {
      preset: 'client',
      plugins: [],
    },
  },
};

export default config;

```

- [x]  `documents` override (exclusion of generate path)
 - [ ] ~handling of `.graphql` files? (with `typed-document-node` under the hood)~
- [x]  remove “(using EXPERIMENTAL preset "gql-tag-operations-preset")” warning
- [x]  ship `client-preset` by default via the CLI package
    - [x]  update `init` accordingly
- [x] TypeScript config first

## Post-release TODOs

- [ ] deprecate `gql-tag-operations-preset` : 

> npm deprecate @graphql-codegen/gql-tag-operations-preset "`gql-tag-operations-preset` is deprecated in favor of `client-preset`"

### CODE REVIEW

**Comment by charlypoly** [comment]
ESM support blocked by same issue as https://github.com/dotansimha/graphql-code-generator/issues/8212

**Comment by n1ru4l** [comment]
Just wanted to mention it here so it does not go "forgotten", we should document how to consume the ypings in your custom graphql fetcher implementation e.g. for library authors, https://github.com/dotansimha/graphql-code-generator/blob/7f2f050256c200d948bd7a9df3e6df72f01eb8bd/examples/typescript-esm/src/executeOperation.ts#L6-L10

**Pull request closed without merging**
