### PR TITLE
Fix the React-Query InfiniteQuery hook error

### PR DESCRIPTION
**Pull request by jrwpatterson**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes the react-query useInfiniteQuery hook bug https://github.com/dotansimha/graphql-code-generator/issues/7052

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

This was cased by returning a function inside the useQuery Function that called the useFetcher hook. This took the hook outside the rules of react hooks. 

this wasn't noticed in the initial commit because we didn't 

## How Has This Been Tested?

We found this when adding a hock inside again this is now testing our production site. 

**Test Environment**:
- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

## Checklist:

- [X] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jeffdetmer** [comment]
I've pulled these changes into our project using patch-package and it is working as expected!

**Comment by jeffdetmer** [comment]
nvm, worked during runtime, but as soon as I attempted to build our project, I'm now getting `Expected 0 arguments, but got 1.ts(2554)` on the generated infinite queries.

```typescript
export const useInfiniteGetAllUsersQuery = <
  TData = GetAllUsersQuery,
  TError = unknown,
>(
  variables?: GetAllUsersQueryVariables,
  options?: UseInfiniteQueryOptions<GetAllUsersQuery, TError, TData>,
) => {
  const query = useFetchData<GetAllUsersQuery, GetAllUsersQueryVariables>(
    GetAllUsersDocument,
  );
  return useInfiniteQuery<GetAllUsersQuery, TError, TData>(
    variables === undefined
      ? ['getAllUsers.infinite']
      : ['getAllUsers.infinite', variables],
    metaData => query({ ...variables, ...(metaData.pageParam ?? {}) }),  // Error: Expected 0 arguments, but got 1. ts(2554)
    options,
  );
};
```

**Comment by jrwpatterson** [comment]
> nvm, worked during runtime, but as soon as I attempted to build our project, I'm now getting `Expected 0 arguments, but got 1.ts(2554)` on the generated infinite queries.
> 
> ```ts
> export const useInfiniteGetAllUsersQuery = <
>   TData = GetAllUsersQuery,
>   TError = unknown,
> >(
>   variables?: GetAllUsersQueryVariables,
>   options?: UseInfiniteQueryOptions<GetAllUsersQuery, TError, TData>,
> ) => {
>   const query = useFetchData<GetAllUsersQuery, GetAllUsersQueryVariables>(
>     GetAllUsersDocument,
>   );
>   return useInfiniteQuery<GetAllUsersQuery, TError, TData>(
>     variables === undefined
>       ? ['getAllUsers.infinite']
>       : ['getAllUsers.infinite', variables],
>     metaData => query({ ...variables, ...(metaData.pageParam ?? {}) }),  // Error: Expected 0 arguments, but got 1. ts(2554)
>     options,
>   );
> };
> ```

if you not there is a change in the fetcher, it's in the updated doco... it just needs to return a variable in the type.

```typescript
export const useFetchData = <TData, TVariables>(
  query: string,
): ((variables?: TVariables) => Promise<TData>) => {
```

**Comment by jeffdetmer** [comment]
ah, I see. then working as intended.

**Comment by jrwpatterson** [comment]
how do I get this in... want to do another bug fix to generateMutationKeyMaker

**Comment by jeffdetmer** [comment]
@dotansimha what is the usual cadence around new releases for fixes like this?  Getting this merged would be a huge help, but if it will take a while, I can plan around it.

**Comment by dotansimha** [comment]
> @dotansimha what is the usual cadence around new releases for fixes like this?  Getting this merged would be a huge help, but if it will take a while, I can plan around it.

Will try to address that in the upcoming days, sorry for the delay!

**Comment by LucasZNK** [comment]
Hi @dotansimha , any updates about this merge? Im getting the same issue

**Review by dotansimha — APPROVED** [review]

**Comment by dotansimha** [comment]
Thanks @jrwpatterson . Sorry for the delay. This looks good.

**Pull request merged**
