### PR TITLE
[React-Query]: Add `options` to exposed fetcher

### PR DESCRIPTION
**Pull request by matha-io**
Add a new `options?: HeadersInit` property on the `useQuery.fetcher` function.

## Description

Most of the time, fetchers can have more information than the `query` & the `variables`.
For example, the GraphQL Request fetcher can receive [`requestHeaders`](https://github.com/prisma-labs/graphql-request/blob/12c2e8d387bf2b4f467335babd2989f0a1d33f53/src/types.ts#L75).
Adding this PR would allow the `prefetchQuery` to be used like this : 

```typescript
queryClient.prefetchQuery(
   useCoursesByUserQuery.getKey(variables),
   useCoursesByUserQuery.fetcher(variables, options), // `Ex: { Authorization: "Bearer xxx" }`
  );
```

Related # (issue)
https://github.com/dotansimha/graphql-code-generator/issues/7370

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Using the same sets of current tests.
I just updated `/packages/plugins/typescript/react-query/tests/react-query.spec.ts` file by adding the change.

**Test Environment**:
- OS: MacOs Big Sur 11.4
- NodeJS: v14.18.2

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by charlypoly — CHANGES_REQUESTED** [review]
Hi @matha-io 👋🏼 

Thanks for your contribution!

I added a change request for the `HeadersInit` usage that should be replaced with `RequestInit['headers']`.

Also, could you provide a live sandbox or repository that contains a live example with your changes?

Thank you!

**Comment by charlypoly** [comment]
@matha-io, also make sure to follow the instructions regarding changesets ([here](https://github.com/dotansimha/graphql-code-generator/pull/7371#issuecomment-1014709232)) in order to bump the impacted package version (as a patch)

Thanks! 🙇🏼

**Comment by matha-io** [comment]
Hey @charlypoly ! I added the changeset + here is the CodeSandbox https://codesandbox.io/s/graphql-codegen-react-query-options-forked-8lp6i?file=/types.ts :)

Supa thanks !

**Comment by matha-io** [comment]
Ok I did the updates :

- Added the failing assertions
- Make the changes on fetchers
- Update the website example for the custom fetcher signatures

I updated the codesanbox : https://codesandbox.io/s/graphql-codegen-react-query-options-forked-8lp6i?file=/types.ts

Thank you again :)

**Review by charlypoly — APPROVED** [review]

**Comment by dottodot** [comment]
Did this ever get released as I'm currently not getting options on my fetcher

**Pull request merged**
