### PR TITLE
Remove extension from operations file import

### PR DESCRIPTION
**Pull request by mvestergaard**
## Description

#7978 added `.js` extensions all over the place. But this one seems wrong. In a typescript project, it will for example generate
`import * as Operations from './UserSelection.gql.js';` resulting in a bunch of errors because the files aren't there (they are `.ts` files)

#8370 #8331

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ardatan** [comment]
This will break the behavior described in here;
https://www.the-guild.dev/graphql/codegen/docs/getting-started/esm-typescript-usage#codegen-configuration

If this flag doesn't work, that flag should be fixed instead of removing `.js` extension.

**Comment by mvestergaard** [comment]
Then someone who knows anything about that ESM stuff should probably pick this up.
It seems to just add the extension always as things are now.

I changed our config to not use external operations to get around the problem for now.

**Review by charlypoly — APPROVED** [review]

**Comment by charlypoly** [comment]
Hi @mvestergaard,

Thank you for your contribution! ⚡ 
Your patch has been released in all impacted packages: https://github.com/dotansimha/graphql-code-generator/pull/8469

**Comment by mvestergaard** [comment]
@charlypoly Seems like there's still issues. The `emitLegacyCommonJSImports` setting is not read from config files. It's always true no matter how you try to set it in configuration.

**Comment by mvestergaard** [comment]
@charlypoly Adding ` --emit-legacy-common-js-imports=false` to the command line is the only way to actually set the value it seems

**Comment by mvestergaard** [comment]
And now the types import gets the .js extension instead, sigh...

**Comment by charlypoly** [comment]
> @charlypoly Adding ` --emit-legacy-common-js-imports=false` to the command line is the only way to actually set the value it seems

@mvestergaard could you share your configuration please?

**Comment by mvestergaard** [comment]
```ts
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: './src/graphql/schema/schema.graphql',
  generates: {
    './src/graphql/schema/index.ts': {
      plugins: [{ add: { content: '/* eslint-disable */' } }, 'typescript'],
    },
    './src/graphql/schema/introspection.ts': {
      plugins: [{ add: { content: '/* eslint-disable */' } }, 'fragment-matcher'],
    },
    './src/graphql/schema/apollo-helpers.ts': {
      plugins: [{ add: { content: '/* eslint-disable */' } }, 'typescript-apollo-client-helpers'],
    },
    './src': {
      documents: './src/**/*.gql.ts',
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.generated.tsx',
        baseTypesPath: './graphql/schema',
      },
      plugins: ['typescript-operations', 'typescript-react-apollo'],
      config: {
        apolloReactHooksImportFrom: '~/graphql/hooks',
        documentMode: 'external',
        importDocumentNodeExternallyFrom: 'near-operation-file',
      },
    },
  },
  config: {
    enumsAsConst: true,
    strictScalars: true,
    defaultScalarType: 'unknown',
    useTypeImports: true,
    emitLegacyCommonJSImports: false,
    scalars: {
      Date: 'Date',
      DateTime: 'Date',
      LocalDateTime: 'Date',
      LocalTime: 'Date',
      UUID: 'string',
      Decimal: 'number',
      Float: 'number',
      Long: 'number',
      Any: 'unknown',
    },
  },
};

export default config;
```

**Comment by charlypoly** [comment]
@mvestergaard can you move the `emitLegacyCommonJSImports: false` at the root of the config?

**Comment by mvestergaard** [comment]
@charlypoly Ok, that does work with toggling it off. But there's an issue with the types import being generated still. With it set to false, it generates 
`import type * as Types from '../../../../graphql/schema.js';`
should be
`import type * as Types from '../../../../graphql/schema';`

It works fine with `emitLegacyCommonJSImports: true` so the logic is probably the wrong way around somewhere, haven't been able to find where.

**Comment by charlypoly** [comment]
> 

You are right, we need to patch the conflict between `useTypeImports` and `emitLegacyCommonJSImports: false`
I've created an issue: https://github.com/dotansimha/graphql-code-generator/issues/8490

**Pull request merged**
