### PR TITLE
docs(flutter-freezed-docs): :memo: updated the flutter freezed plugin…

### PR DESCRIPTION
**Pull request by Parables**
- [x ] This change requires a documentation update

### CODE REVIEW

**Comment by Parables** [comment]
@charlypoly, here the the updates for the flutter-freezed-plugin as promised

**Comment by charlypoly** [comment]
@Parables, I fixes the API doc: https://graphql-code-generator-4vbqdw753-theguild.vercel.app/plugins/dart/flutter-freezed

**Comment by Parables** [comment]
@charlypoly, I really appreciate that you accept my PRs and fix them for me.

It feels so rewarding just  seeing my work out there and npm says the plugin get 46 downlaods /week  on average.

I feel so motivated to continue working on this plugin and extend it to be something like KitQL but for Flutter

PS: I am willing to help out anyway I can. Just assign me to any task and I will make sure it get done.

**Comment by charlypoly** [comment]
Hi @Parables,

I'm glad that we got your work published! 🎉 
I'll let you know if we can improve codegen for the Dart ecosystem 😉 

Thank you!

**Comment by Parables** [comment]
I will be looking forward to that.

Thank you so much

**Pull request merged**
