### PR TITLE
Introduce typescript-generic-sdk plugin

### PR DESCRIPTION
**Pull request by akozhemiakin**
Possible solution for #2415 which abstracts over concrete graphql client implementation

### CODE REVIEW

**Comment by akozhemiakin** [comment]
It would be awesome to have higher kinded types feature in typescript to abstract over wrapper type. For example apollo return result in some wrapper and with this generic implementation we forced to unwrap it in requester.

**Comment by dotansimha** [comment]
Very nice! I think the effort of having to create a wrapper for client is fine. 
I'll review it soon :) 

Thanks @akozhemiakin !

**Comment by akozhemiakin** [comment]
Thank you for the response and for the great project. I just pushed another commit which allows to pass options to the requester.
Also I really want to find a way to generalize output type. Maybe I'll give a try to fp-ts HKT or something like that. In Scala it would be painless, but Typescript, unfortunately doesn't have so much power it its type system yet.

**Comment by akozhemiakin** [comment]
Btw, here is the Apollo requester implementation created to be used with this plugin:
https://gist.github.com/akozhemiakin/731b0c1e99eb89b01f80f08f9146b6b6

**Comment by dotansimha** [comment]
Sorry for the delay, @akozhemiakin . 
We are currently working on a library that could use that feature, so I'm reviewing and testing it now. I assume we can merge this very soon.

**Comment by dotansimha** [comment]
Merged, I also pushed a fix to align the version number in `package.json`.
Alpha will be available very soon.

**Comment by dotansimha** [comment]
Alpha version now available: `1.12.2-alpha-085fe906.18`.

**Comment by DrChrispoper** [comment]
I can only find documentation for `typescript-graphql-request`. Does this mean there is no `typescript-generic-sdk` or as https://github.com/dotansimha/graphql-code-generator/issues/3458 sugguests there is just no documentation for it. I am looking to use it with Apollo Client.

**Comment by akozhemiakin** [comment]
@DrChrispoper First of all, take my excuses for not providing docs along with the original request, I'll try to schedule it.

Meanwhile, have you seen this gist?
https://gist.github.com/akozhemiakin/731b0c1e99eb89b01f80f08f9146b6b6

It is how we use `typescript-generic-sdk` with Apollo in our project.

**Comment by DrChrispoper** [comment]
Thanks for reaching out so fast, yeah I've seen it thanks! The docs would be great mainly to know that it exists hehe!

**Pull request merged**
