### PR TITLE
Comment per each section

### PR DESCRIPTION
**Pull request by kamilkisiela**
@dotansimha @dotansimha @dotansimha what do you think about that?

### CODE REVIEW

**Comment by dotansimha** [comment]
Looks good! 
Just fix the ci :)

**Comment by kamilkisiela** [comment]
@dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha

**Comment by dotansimha** [comment]
@kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela @kamilkisiela

**Comment by kamilkisiela** [comment]
@dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha @dotansimha

**Pull request merged**
