### PR TITLE
feat: support type imports

### PR DESCRIPTION
**Pull request by SimenB**
Very rough start on #3695. Not sure how you want to handle this. I'll probably just do the ones we need at work (which means Apollo TS), but it should be fine to expand as we go?

(is there some watch mode I can run that builds as we go? right now I do a full `yarn build` every time I change something, which seems suboptimal)

### CODE REVIEW

**Comment by SimenB** [comment]
Only reason for an option rather than being default behavior is that it requires TS 3.8. Maybe some "minimum TS version" rather than an explicit option makes more sense?

**Comment by dotansimha** [comment]
This is awesome! Thank you @SimenB ! 

This could work, and could be optional via configuration. What about importing enums and other things? how is it effected?

**Comment by SimenB** [comment]
Are enums imported as values anywhere? The test should probably try to compile the module we generate with `isolatedModules: true` and `importsNotUsedAsValues: error`. I don't think I know enough about your setup to add that, though

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function

**Comment by ardatan** [comment]
For example, there are const enums used as values not types. So `import type` would break this behavior.

**Comment by SimenB** [comment]
`const enum` aren't supported by `isolatedModules` regardless, so I wouldn't want them 😃

**Comment by vatosarmat** [comment]
Any chances this useful feature to be merged? :smiley_cat: 
Since it is optional and disabled by default, it shouldn't break anything for anyone.

**Comment by dotansimha** [comment]
@vatosarmat merging :) 
I'm merging it now, and will push some fixes soon to make sure all codebase supports that. 

Thanks @SimenB , sorry it took so long.

**Comment by SimenB** [comment]
Thanks @dotansimha! I believe this was still incomplete, happy to hear you'll fix the missing parts 👍

I wanted to add some tests with `isolatedModules: true` and `importsNotUsedAsValues: error`, but didn't get around to it. I believe such tests would be quite useful to ensure no regressions. Never got around to it, though 😅

**Comment by SimenB** [comment]
Tested this out now in the new release, and it works for some cases. However, it does not affect

- `from 'graphql'`
- `from '@apollo/react-common'`
- imports from `near-operation-file`'s `baseTypesPath`
- fragment imports (possibly from `near-operation-file`?)

@dotansimha My OSS backlog is really long right now, so I won't be able to work on this. 🤞 you can 😀

**Pull request merged**
