### PR TITLE
Fix validation of enum list args for Java

### PR DESCRIPTION
**Pull request by optionsome**
## Description

* Adds a failing test for generated Java enum list args
* Fixes the issue by returning the enums if args contain an Iterable<String> instead of Iterable<Enum>

Related #7002

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):

Can be found in the linked issue.

## How Has This Been Tested?

Tested through the added unit test and in a project that has query arguments which contain a list of enum options.

**Test Environment**:
- OS: Debian 10
- `@graphql-codegen/java`: 
- NodeJS: 12.22.7

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by optionsome** [comment]
Should I create a changeset here?

**Comment by optionsome** [comment]
@dotansimha I think this pull request should be ready for review

**Comment by t2gran** [comment]
We (Entur AS) would love to see this fixed! Thank you for providing this framework.

**Review by charlypoly — APPROVED** [review]

**Comment by charlypoly** [comment]
Hi @optionsome, thank you very much for your contribution! ⚡ 

I'll ping when it gets released 📦

**Pull request merged**
