### PR TITLE
Add support for internal enum values in typescript template

### PR DESCRIPTION
**Pull request by dobesv**
Fixes https://github.com/dotansimha/graphql-code-generator/issues/576

### CODE REVIEW

**Comment by dotansimha** [comment]
NICE! Thanks @dobesv !

**Comment by Slessi** [comment]
I got round to using this today, documentation is incorrect as described in this case:

```json
    prepend: [
        "import { CustomScalarType } from './custom-types';"
        "import { AnotherCustomScalarType } from './another-custom-types';"
        "import { CustomScalarType } from './custom-types';",
        "import { AnotherCustomScalarType } from './another-custom-types';",
        "import { WeekDay } from './WeekDay';"
    ],
    scalars: {
        "CustomScalar": "CustomScalarType",
        "AnotherCustomScalar": "AnotherCustomScalarType"
    },
    enums: {
      "WeekDay": {
        "SUNDAY": "WeekDay.Sunday",
        "MONDAY": "WeekDay.Monday",
        "TUESDAY": "WeekDay.Tuesday",
        "WEDNESDAY": "WeekDay.Wednesday",
        "THURSDAY": "WeekDay.Thursday",
        "FRIDAY": "WeekDay.Friday",
        "SATURDAY": "WeekDay.Saturday",
      }
    }
```

The generated `WeekDay` will conflict with the imported `WeekDay`. Trivially fixed by doing `import { WeekDay as SomethingElse }`.

But wouldn't it have been simpler if this worked like `scalars`?

```json
    prepend: [
        "import { CustomScalarType } from './custom-types';",
        "import { CustomEnumType } from './custom-types';"
    ],
    scalars: {
        "CustomScalar": "CustomScalarType"
    },
    enums: {
      "CustomEnum": "CustomEnumType"
    }
```

My enum is already defined somewhere, don't want to update `gql-gen.json` everytime I update my enum

**Comment by dobesv** [comment]
Fair points.  In my case I wrote a wrapper around the generator so that I dynamically generate the config with the enums and their value in it to work around this exact issue.

**Comment by dobesv** [comment]
Which I think supports your argument that it should be possible to just reference and existing enum.

**Comment by dobesv** [comment]
I suppose it might not be too hard to add this feature you describe, if the enum definition is a string instead of a mapping then just assign it like "type WeekDay = WeekDayEnum" if the names aren't the same or emit nothing if they are the same.

**Comment by dobesv** [comment]
That said, I'm happy with the status quo so don't wait for me to address this...

**Comment by Slessi** [comment]
Would love to do it myself if only there was a contributing guide - `yarn test` fails for me before I even edit anything on master branch, so not sure where to start

**Comment by dotansimha** [comment]
Hi @Slessi 
Please refer to my comment here: https://github.com/dotansimha/graphql-code-generator/pull/853#issuecomment-439269193

**Pull request merged**
