### PR TITLE
6245 missing fragment imports fix

### PR DESCRIPTION
**Pull request by gilgardosh**
Related #6245 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by dotansimha** [comment]
@gilgardosh can you please rebase? And this is still a draft, or it's ready for a review?

**Comment by gilgardosh** [comment]
@dotansimha rebased and ready for review

**Comment by ertrzyiks** [comment]
@gilgardosh could you help getting the alpha release package for testing? If I understand https://github.com/dotansimha/graphql-code-generator/pull/6290#issuecomment-877768244 correctly it's a matter of adding the changeset entry.

**Comment by gilgardosh** [comment]
@ertrzyiks  Here you go:
@graphql-codegen/near-operation-file-preset@1.18.6-alpha-96980211a.0

**Pull request merged**
