### PR TITLE
Revert "[kotlin] remove constructor method from generated code (#3156)"

### PR DESCRIPTION
**Pull request by danielw93**
This reverts commit b0582584a9beeedf72d416582d713d7099753906.

Fix for Issue #4820

### CODE REVIEW

**Comment by dotansimha** [comment]
Reverting this is the only solution? I believe there should be other options to fix that. 
@omuomugin can you please take a look?

**Comment by danielw93** [comment]
Hey, thanks for the quick reply!
I'm almost certain that the changes by @omuomugin could never have worked because they violate Kotlin's type system.
However I'm a bit intrigued that no one else seems to have run into these problems before, during the past half year...you'd think with >3000 weekly downloads for graphql-codegen/kotlin others would have reported this problem

**Comment by danielw93** [comment]
For easier review, here is a Repl to illustrate the problem: https://repl.it/@xwalled/CodegenCompilerProblem

Lines 20-22 is what versions of graphql-codegen/kotlin prior to 1.10.0 would have created from the query definition in lines 9-11.
Line 29 is what the same query definition gets converted to, as of v.1.10.0. 

To see the desired behavior Run the Repl once (no output is shown, but we get no compiler errors).

To see the error behavior, comment out lines 20-22 and uncomment line 29. Then run the Repl again.
=> you'll get a compiler error from line 36, where we try to instantiate the `QueryItemArgs` 
     from the graphql arguments we received.
 > error: type mismatch: inferred type is Map<String, Any> but Long was expected

**Comment by dotansimha** [comment]
Got it. Thank you @danielw93 :)

**Pull request merged**
