### PR TITLE
fix optional input type fields for graphql-input

### PR DESCRIPTION
**Pull request by jvolonda42**
## Description

When using typescript-type-graphql, the optional fields from an input are not optional

Related #8001 

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Environment**:

- OS: [Linux]
- NodeJS: [16.15.1]
- graphql version: [15.3.0]
- @graphql-codegen/cli version(s): [ 2.6.2]
- @graphql-codegen/typescript-type-graphql version(s): [ 2.2.14]

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
can you please add a test for this?

**Comment by jvolonda42** [comment]
Hello @saihaj I have updated test accodingly

**Comment by jvolonda42** [comment]
My bad missed a console.log in tests now should be good.

**Comment by saihaj** [comment]
Thanks @jvolonda42! 🎉

**Comment by jvolonda42** [comment]
Thanks you for being do reactive @saihaj

**Pull request merged**
