### PR TITLE
New plugin: TypeScript Vue Apollo Smart Operations

### PR DESCRIPTION
**Pull request by sgarner**
## Description

Hi :wave: I have created a new plugin for generating TypeScript-typed operation functions for Vue Apollo.

This differs from the existing "TypeScript Vue Apollo" plugin because that uses the Composition API, whereas this new plugin is suited to projects that are using Vue Apollo's original ["Option" API](https://v4.apollo.vuejs.org/api/smart-query.html#options).

It generates code like the following:

```ts
export const useCommentQuery = createSmartQueryOptionsFunction<CommentQuery, CommentQueryVariables, ApolloError>(
  CommentDocument
);
```

This can then be used in a Vue component like:

```ts
{
  apollo: {
    comment: useCommentQuery({
      // variables will be properly typed here!
      variables: {
        repoFullName: 'foobar'
        limit: 1
        offset: 0
      },
      loadingKey: 'loading',
      fetchPolicy: 'no-cache',
    }),
  }
}
```

The plugin relies on some functions that I've published separately to NPM in the [`vue-apollo-smart-ops`](https://www.npmjs.com/package/vue-apollo-smart-ops) package.

Note I based my plugin implementation on the code from the `typescript-vue-apollo` plugin, so thanks to whoever contributed that one for giving me a head start. 👍 

## Type of change

New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tests included in PR.

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @sgarner ! Thank you for creating it. Can you please add a changeset (run `yarn changeset` and it will guide you)? 
I hope to review this in a few days :)

**Comment by sgarner** [comment]
> Hi @sgarner ! Thank you for creating it. Can you please add a changeset (run `yarn changeset` and it will guide you)?
> I hope to review this in a few days :)

Thanks @dotansimha - I've added a changeset now. Please note:

1. I set the new plugin as a major release, which I presume will make it v1.0.0. Making it a pre-release like v0.1.0 could also be an option - what's the project's normal practice here?

2. The tool said the `typescript` plugin has changed, though I'm not sure why. I included it in the changeset anyway.

**Comment by NotHolst** [comment]
What the status of this, and also why doesn't the regular vue-apollo typed options/variables?

**Comment by sgarner** [comment]
> What the status of this, and also why doesn't the regular vue-apollo have typed options/variables?

It is awaiting a review from @dotansimha when he has time 🙂

**Comment by dotansimha** [comment]
Thank you @sgarner , sorry for the delay! 
I'm not sure why, but GH prevents me from pushing into your PR. Can you please rebase/merge master and then we can get this one merged? :)

**Comment by sgarner** [comment]
@dotansimha I have merged master and resolved the conflicts now. 🙂  Thanks!

**Comment by dotansimha** [comment]
> @dotansimha I have merged master and resolved the conflicts now. 🙂 Thanks!

It's available now as a package, thank you so much!

**Pull request merged**
