### PR TITLE
feat(presets/client): support `enumsAsConst` option

### PR DESCRIPTION
**Pull request by azu**
## Description

Add `enumsAsConst` to client presets.

Related 

- https://github.com/dotansimha/graphql-code-generator/issues/8562#issuecomment-2137815225
- https://github.com/dotansimha/graphql-code-generator/issues/9072

Edit:

This PR is duplicated of https://github.com/dotansimha/graphql-code-generator/pull/9574, but this includes a test.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Add Unit Test

## How Has This Been Tested?

- Add a test case for `enumsAsConst`
- Run `npm test`

**Test Environment**:

- OS: macOS
- `@graphql-codegen/...`: latest
- NodeJS:v18.19.0

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

client preset already support `enumsAsType`.
I think that it should support `enumsAsConst` too.

- [feat(preset/client): allow use of enumsAsType config option by panusoi · Pull Request #8472 · dotansimha/graphql-code-generator](https://github.com/dotansimha/graphql-code-generator/pull/8472)
- [`enumsAsTypes` can't be used with `client-preset` · Issue #8471 · dotansimha/graphql-code-generator](https://github.com/dotansimha/graphql-code-generator/issues/8471)

### CODE REVIEW

**Comment by azu** [comment]
Ah, I notice that this PR is duplicated of https://github.com/dotansimha/graphql-code-generator/pull/9574, but this PR includes a test.

**Comment by azu** [comment]
@n1ru4l Thanks.
I've added enumsAsConst to website/src/pages/plugins/presets/preset-client.mdx
https://github.com/dotansimha/graphql-code-generator/pull/9981/commits/c9a3511c6b5ce8f58b6740a3daafede5c4c9d22f

**Comment by SSmietana** [comment]
Anything holding this up? This would be a very helpful feature

**Comment by nebbles** [comment]
@azu maybe worth re-requesting review from @n1ru4l now that you've made the requested changes? Would be great to see this land in client-preset.

**Comment by sampsonjoliver** [comment]
+1 to this change, this would resolve several headaches for my org.

**Comment by SimonTernoir** [comment]
Great work @azu, this would be an amazing change for us as well if it could get merged!
I’d be more than happy to help if needed to make this happen @n1ru4l

**Review by eddeee888 — APPROVED** [review]
Thank you!

**Pull request merged**
