### PR TITLE
feat(typescript-vue-urql): support externally imported DocumentNodes

### PR DESCRIPTION
**Pull request by benkroeger**
## Description

clones related code and tests from plugin `typescript-urql` into `typescript-vue-urql`

Related #7360

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- validate config properties
- validate expected output / generated code

**Test Environment**:
- OS: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
- "@graphql-codegen/typed-document-node": "2.2.2"
- "@graphql-codegen/typescript": "2.4.2"
- "@graphql-codegen/typescript-operations": "2.2.2"
- "@graphql-codegen/typescript-vue-urql": "2.2.2"
- "@graphql-typed-document-node/core": "3.1.1"
- NodeJS: 14.18.1

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ardatan** [comment]
Looks great! Could you create a changeset with `yarn changeset`?

**Comment by benkroeger** [comment]
> Looks great! Could you create a changeset with `yarn changeset`?

I could... but is this a minor or patch update? Since the feature has been in the docs for a long time and just didn't work, I'd expect this to be a patch?!

**Comment by benkroeger** [comment]
changeset with patch level added

**Comment by benkroeger** [comment]
@ardatan do you need anything else from me to take this forward?

**Review by charlypoly — APPROVED** [review]

**Comment by charlypoly** [comment]
Thank you for your contribution, @benkroeger!

I'll ping you when it is released 📦

**Pull request merged**
