### PR TITLE
import-types-preset

### LINKED ISSUE #2165: [ts-react-apollo] Types should able to import from other file when it is the only plugin used
**Is your feature request related to a problem? Please describe.**

If we need to generate an independent file with only `typescript-react-apollo` plugin, it needs types generated from other plugins to be imported externally. 

**Describe the solution you'd like**

For example, if we have an option like `typesImport: @external-file` in `typescript-react-apollo` plugin

```codegen.yml
generates:
  packages/sample-client-state/src/interfaces/generated-models.ts:
    documents: "packages/sample-client-state/src/**/*.gql"
    schema: 
      - ./packages/sample-client-state/src/**/*.graphql
    config:
      enumValues: ./enum
      constEnums: true
      skipTypename: true
      noNamespaces: true
      contextType: ./context#MyContext
      typesPrefix: I
      withMutationFn: false
      withHOC: false
      withComponent: false
    plugins:
      - add: |
          /* tslint:disable */
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-react-apollo
  packages/sample-client-react/src/generated/models.tsx:
    documents: "packages/sample-client-state/src/**/*.gql"
    schema: 
      - ./packages/sample-client-state/src/**/*.graphql
    config:
        typesPrefix: I
        typesImport: @external-file
        withMutationFn: true
        withHOC: true
        withComponent: true
        noGraphQLTag: true
    plugins:
      - typescript-react-apollo
```

generated `.ts` file
```
.....
export type ISelectFileMutationVariables = {
  content?: Maybe<ISelectEditor_Input>;
};

export type ISelectFileMutation = Pick<IMutation, "selectFile">;
....
```

generated `.tsx` file
```
import { ISelectFileMutation, ISelectFileMutationVariables } from '@external-file'
....
export type ISelectFileMutationFn = ReactApollo.MutationFn<
  ISelectFileMutation,
  ISelectFileMutationVariables
>;
export type SelectFileComponentProps = Omit<
  ReactApollo.MutationProps<ISelectFileMutation, ISelectFileMutationVariables>,
  "mutation"
>;

export const SelectFileComponent = (props: SelectFileComponentProps) => (
  <ReactApollo.Mutation<ISelectFileMutation, ISelectFileMutationVariables>
    mutation={SelectFileDocument}
    {...props}
  />
);

export type ISelectFileProps<TChildProps = {}> = Partial<
  ReactApollo.MutateProps<ISelectFileMutation, ISelectFileMutationVariables>
> &
  TChildProps;
export function withSelectFile<TProps, TChildProps = {}>(
  operationOptions?: ReactApollo.OperationOption<
    TProps,
    ISelectFileMutation,
    ISelectFileMutationVariables,
    ISelectFileProps<TChildProps>
  >
) {
  return ReactApollo.withMutation<
    TProps,
    ISelectFileMutation,
    ISelectFileMutationVariables,
    ISelectFileProps<TChildProps>
  >(SelectFileDocument, {
    alias: "withSelectFile",
    ...operationOptions
  });
}
......
```
That way we have a `non-react` package that could be used for various purpose and for `react` component, we can generate a separate `.tsx` file by importing any types that required to generate `.tsx` through importing externally.

**Describe alternatives you've considered**

The alternative would be using `add` plugin and add the types manually which would be a cumbersome task to update the types every time types are changed or updated.
**Additional context**

### PR DESCRIPTION
**Pull request by veeramarni**
To fix #2165

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank @veeramarni , and sorry for the delay.
Can you please explain why do we need a new preset for this? 
If the goal is to allow importing from other files, isn't a configuration enough?

**Comment by dotansimha** [comment]
Awesome, thanks!

**Comment by veeramarni** [comment]
@dotansimha thank you :)

**Comment by helderco** [comment]
Is there documentation for this, like https://graphql-code-generator.com/docs/presets/near-operation-file?

**Comment by dotansimha** [comment]
@helderco I added basic docs for it, it will be available soon (with the next deploy)

**Pull request merged**
