### PR TITLE
Add gqlImportFrom option

### LINKED ISSUE #1342: Configurable `gql` import
**Is your feature request related to a problem? Please describe.**
It's pretty much [a recommended way](https://github.com/facebook/create-react-app/pull/5481) to use `graphql.macro` for loading graphql files or inlining documents. Since CRA2.0 has `babel-plugin-macros` includes it's a fairly cheap optimization of runtime code.

**Describe the solution you'd like**
Add configuration option `gqlImportFrom` to specify where to find `gql`.

**Describe alternatives you've considered**
Perhaps a boolean flag directly for a macro variant?

### PR DESCRIPTION
**Pull request by FredyC**
Related #1342 

Once again I am not sure if there is a better way to handle the default config.

Edit: On the contrary to a drafted solution, I had to opt for configuring whole import line because `graphql.macro` does not have a default export.

### CODE REVIEW

**Comment by IanVS** [comment]
I think this could also fix https://github.com/dotansimha/graphql-code-generator/issues/1321, right?  Although, it feels a little brittle to specify the whole import line.

**Comment by FredyC** [comment]
> Although, it feels a little brittle to specify the whole import line.

I kinda agree it was just first shot, I am open to suggestions, but let's not build an AI for one code line :)

**Comment by dotansimha** [comment]
Looks good. @FredyC please rebase and then I'll merge it :)

**Comment by FredyC** [comment]
Wow, did not know it's possible to resolve conflicts within the GitHub, very neat :)

**Pull request merged**
