### PR TITLE
Put configuration into a codeblock to make it more readable

### PR DESCRIPTION
**Pull request by JoeSchr**

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @JoeSchr , but is there a reason to do that? 
I mean, the configuration partial uses code block where needed, and it's formatted as list. See how the result looks like: https://graphql-code-generator.com/docs/plugins/typescript-vue-apollo#configuration

**Comment by JoeSchr** [comment]
On my side it looks like this:
image

instead of e.g.: https://graphql-code-generator.com/docs/plugins/typescript-mongodb
image

which I find way more readable and quicker to comprehend

**Comment by dotansimha** [comment]
It had a missing close block for the code (```), I updated it in the source, and it will be in the website after next deployment. 

Thanks @JoeSchr !

**Comment by JoeSchr** [comment]
👍

**Pull request closed without merging**
