### PR TITLE
bump required version of @graphql-tools/utils

### PR DESCRIPTION
**Pull request by capaj**
otherwise we get this one:
```
$ graphql-codegen --config codegen.yml
/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502
const getCachedDocumentNodeFromSchema = utils.memoize1(utils.getDocumentNodeFromSchema);
                                              ^

TypeError: utils.memoize1 is not a function
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/cli/bin.js:29:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

It was not

**Test Environment**:
- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ardatan** [comment]
Good catch! But I think it's been added in 8.2.0;
https://unpkg.com/@graphql-tools/utils@8.2.0/index.js
So could you update it then we can merge and release?

**Comment by capaj** [comment]
you want to lower the version to 8.2.0 rather than using the latest 8.5.2? Why?

**Comment by ardatan** [comment]
@capaj Because it is the least required version for that package and as far as I know having `^` in the version is to define least request version in order to deduplicate lock entries and decrease the number of installed versions of that package as much as possible. Maybe I am completely wrong.

**Comment by capaj** [comment]
No you are not wrong. Defining it as `^8.2.0` will allow for slightly greater chance of not having to download multiple versions. My problem is I have manually tested this only with 8.5.2, so I only know it will work ok with that version.

> deduplicate lock entries and decrease the number of installed versions of that package

IMHO this is a job for package manager. As a developer, you shouldn't need to think about this.

If some other package has `^8.2.0` as well, the `8.5.2` will suffice for both packages.
If some other package has `8.2.0` then it will need to install a second version because 8.5.2 won't satisfy that.

**Comment by ardatan** [comment]
Anyway it doesn't matter that much. Could you add a changeset so we can merge and release?

**Comment by capaj** [comment]
reopened as #6973

**Pull request closed without merging**
