### PR TITLE
Add operation export name

### PR DESCRIPTION
**Pull request by aspirisen**
This PR is relative to this issue https://github.com/dotansimha/graphql-code-generator/issues/3949

It allows you to add operation name to output file.

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @aspirisen ! 

This should work only with `.d.ts` output, right? it won't work with `.ts` extension? because some configuration flags might effect that as well.

Also, have you checked `graphql-let` (https://github.com/piglovesyou/graphql-let#readme) package? it should does that automatically as far as I know.

**Comment by aspirisen** [comment]
@dotansimha  Yes, it would work only in `d.ts`files, but it is up to user because there is a flag for that. But if user uses only types this flag will help him to import everything from one file.

I checked `graphql-let` and there is one issue that stops me using it `https://github.com/piglovesyou/graphql-let/issues/60`

**Comment by dotansimha** [comment]
If you need to have a more strict path in the module declaration, you can use this configuration: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/graphql-files-modules/src/index.ts#L6-L25 (it's not in the docs, we need to update it). 

I afraid that the name you set for this variable might conflict with other plugins, we need to check that.

**Comment by aspirisen** [comment]
@dotansimha what variable do you mean, the const export in `d.ts`?

**Comment by dotansimha** [comment]
I think we can get this one merged. Thank you @aspirisen , sorry it took so long!

**Pull request merged**
