### PR TITLE
Output custom template output to --out

### PR DESCRIPTION
**Pull request by micimize**
Address #209, as well as:
* preserve directory structure to `--out` 
* make `ts.{ schema, documents }.handlebars` work without a prefix
  (e.g. `ts.schema.handlebars` => `schema.ts`)
* automatically `registerPartial` custom templates without breaking normal partial registration (`registerPartial(filename.split('.').reverse()[1], template)`)
* mark comments safe to avoid url escaping
* fixes some links in the docs and add relevant docs for the included changes

### CODE REVIEW

**Comment by dotansimha** [comment]
@micimize 
It sounds good. Only issue is that we need to address this scenario:
```
- a/
    ts.schema.handlebars
- b/
    ts.type.handlebars
```

What will `--out` should do? because there are multiple directories with templates...  The existing implementation will output the file to the same directory as the template

**Comment by micimize** [comment]
@dotansimha great, I'll get this PR up to scuff so it can be merged and doesn't break everything.
For the directory structure - I've now started on that locally, and have the files outputting to the same relative directory structure. Am currently trying to solve the `#eachImport` module resolution problem, as it isn't directory structure aware

**Comment by micimize** [comment]
It looks like it would require breaking template name parsing and handling into separate batch processes, and then passing a resolution map. Might be a good idea, but seems better done as a separate PR. Will update the custom templates docs on how to handle import paths

**Comment by micimize** [comment]
@dotansimha fixed the parts that were breaking the CI / `yarn test` and updated the description & docs, so it's good to go

**Comment by minheq** [comment]
any update on this?

**Comment by dotansimha** [comment]
Great work @micimize !

**Pull request merged**
