### PR TITLE
Removed the unnecessary call to print in the graphql-request plugin.

### PR DESCRIPTION
**Pull request by AradAral**
Related #5614

### CODE REVIEW

**Comment by ardatan** [comment]
Could you add a changeset by running `yarn changeset`? @AradAral

**Comment by AradAral** [comment]
> Could you add a changeset by running yarn changeset?

Oh yeah sorry, sure :)
I'm new to the JS ecosystem, I did `yarn changeset` and completed the steps, a file `.changeset/fresh-ligers-look.md` was generated. What should I do now? Commit it?

**Comment by ardatan** [comment]
Yes @AradAral :) It helps us for versioning and creating changelogs of packages individually.

**Comment by AradAral** [comment]
@ardatan Can you check this out Arda?
Are there any further changes needed?

**Comment by ardatan** [comment]
Waiting for @dotansimha 's review :)

**Comment by dotansimha** [comment]
Since `v3.0.0`, `graphql-request` does support `DocumentNode`, so we can safely assume now that we can pass `string | DocumentNode`. Thank you for making this adjustment @AradAral !

**Pull request merged**
