### PR TITLE
feat: configuration of default scalar type

### LINKED ISSUE #5274: Support configuration of default scalar type for custom scalars
**Is your feature request related to a problem? Please describe.**

When generating typescript code, I would prefer that the `Scalars` type mapping for custom scalars default to `unknown` rather than `any` (better type safety; forces explicit typecasting; makes missing custom scalar type overrides more obvious). It's conceivable that there may be similar desires when generating code in other languages too.

**Describe the solution you'd like**

A new config option for the typescript code generator that allows me to set the default scalar type to `unknown`. This could possibly be a string config that technically supports any type to be specified, or a boolean config specific to typescript code generation only that restricts the options to `any` or `unknown`. 

I think a string option might be more preferable to generally support this option for other languages. Even within typescript, it may be desirable to use `never` as the default type to more strictly require that custom scalars be given type mappings.

**Describe alternatives you've considered**

Hackishly post-processing the output of the code generator to find/replace `any` with `unknown`. Doesn't seem worth the effort to do it properly.

**Additional context**

I have poked around the source code and found that there is a `buildScalars()` method in `packages/plugins/other/visitor-plugin-common/src/utils.ts` with a `defaultScalarType` parameter that defaults to `'any'`. I don't understand the structure of this project well enough to figure out the "right" way to make the change myself, but I would recommend starting by making the `defaultScalarType` required (no default value; because `any` is not a good default for ALL languages), then following the compiler errors to every usage of `buildScalars()` and make a case-by-case decision on whether to pass a hard-coded value for `defaultScalarType`, or require it to be passed down from the next level up in the call stack, grabbed from config, etc.

### PR DESCRIPTION
**Pull request by andreialecu**
## Description

Allows defining the scalar type to use for unknown scalars, instead of `any`.

Additionally, allows setting a config value `strictScalars: true`, which will result in the generator throwing an error if it encounters a scalar that wasn't defined in the `scalars` config field.

Related #5274

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

N/A

## How Has This Been Tested?

Added unit tests.

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

I chose to create a new wrapper method for `buildScalars` and keep the changes minimal. The reason for the new method is to ensure that there are no breaking changes. I wasn't sure if `buildScalars` is exported and used by other external plugins.

### CODE REVIEW

**Comment by dotansimha** [comment]
This looks amazing. Thank you so much @andreialecu ! 
Can you please add a changeset file (run `yarn changeset` and it will guide you). I think we need to bump all touched and dependent packages. This will also allow us to have an alpha version for testing purposes before merging this.

**Comment by andreialecu** [comment]
@dotansimha done.

**Comment by andreialecu** [comment]
@dotansimha bump :)

**Comment by raveclassic** [comment]
Hey guys, this is awesome! Looking forward to seeing this released!

**Comment by dotansimha** [comment]
Hi @andreialecu ! Sorry for the delay. This looks great, merging and will cut a release very soon!

**Comment by UselessPickles** [comment]
@andreialecu While you were digging around the code for this, did you see any easy opportunities for adding another strict check that fails if the `scalars` config contains entries for custom scalars that do not exist in the schema? I would expect `strictScalars: true` to be fully strict, requiring the `scalars` config to provide mappings for exactly all custom scalars in the schema. No more, no less.

**Comment by Urigo** [comment]
@UselessPickles could you create a new issue for that?

**Pull request merged**
