### PR TITLE
Fix SubscriptionSubscribeFn interface

### PR DESCRIPTION
**Pull request by const86**
The subscribe callback of subscription 'foo' should normally
return an object like { foo: value } where value is of type
of the subscription. Add that wrapping layer to the interface.

### CODE REVIEW

**Comment by const86** [comment]
This should address bug #1632.

**Comment by dotansimha** [comment]
Hi @const86 ! Thank you for your contribution! 
Does your PR is a breaking change? because I noticed that you added the new generics in between and not as last.

/cc @kamilkisiela can you please take a look?

**Comment by const86** [comment]
I'm changing existing types, so I guess it's a breaking change. Unless you consider previous code so broken that nobody could used it anyway.

**Comment by dotansimha** [comment]
@const86 my point is, that you changed it from `export interface ISubscriptionResolverObject<Result, Parent, Context, Args>` to `export interface ISubscriptionResolverObject<Result, Key: string, Parent, Context, Args>` , which is a breaking change for the API, because if someone uses it as `ISubscriptionResolverObject<A, B, C>` it will be invalid now. 
The non-breaking way of doing that is `export interface ISubscriptionResolverObject<Result, Parent, Context, Args, Key: string>`. But it all the usages of those interfaces are internal, then it's fine (but I'm not so sure about that)

**Comment by const86** [comment]
I see. Tell me if I should move new argument to the end of the list to make things easier.
I believe, it will be a breaking change in that interface anyway, unless that new last argument is optional with  default resulting in the old behavior. Overall behavior is incompatible with current version. If somebody has subscription resolvers matching generated interface, they will see errors with new version.

**Comment by dotansimha** [comment]
I see, thanks @const86 ! 
@ardatan @kamilkisiela can you please review this?

**Comment by DanielMSchmidt** [comment]
Awesome work @const86, I was about to dig into how to do a PR like this 👍

**Comment by const86** [comment]
@kamilkisiela, I've update the PR. Now subscription resolver is a union of two interfaces. One is like the old one, with even relaxed result type of `subscribe`. That doesn't have to be `TResult`, only the `resolve` has to.
Another is like my first option: `subscribe` yields `{ [name]: TResult }` and `resolve` is optional. If you still want to provide `resolve`, it must again return a `TResult`.
I guess, now we can even call it backward compatible.

**Comment by const86** [comment]
@kamilkisiela, @dotansimha, anything else I should do?

**Comment by dotansimha** [comment]
@kamilkisiela what do you think? 

If someone wants to test it, I pushed the changes to the source repo so it will be available as alpha release: `1.2.1-alpha-0a69c2be.18`

**Comment by Yuyz0112** [comment]
@dotansimha I have tested the `1.2.1-alpha-0a69c2be.18` release and it works in my situation.

Is there any chance we can merge this into the master branch?

**Comment by dotansimha** [comment]
@kamilkisiela can you please take another look at this issue?

**Pull request closed without merging**
