### PR TITLE
[typescript-react-query] Allow passing `headers` to `graphql-request`

### PR DESCRIPTION
**Pull request by dan-lee**
## Description

With `graphql-request` it's possible to pass in `headers` on a per request basis. With the current implementation, this can not be achieved with `@graphql-codegen/typescript-react-query`. This PR adds an optional parameter `headers` to the hook and fetcher.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Existing tests have been extended

**Test Environment**:
- OS: macOS
- `@graphql-codegen/...`: 
- NodeJS: 

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ardatan** [comment]
How about adding all other props of `RequestInit` ?

**Comment by dan-lee** [comment]
@ardatan The third parameter of `request` only allows `headers` to be passed in: https://github.com/prisma-labs/graphql-request#passing-headers-in-each-request

**Comment by dotansimha** [comment]
Hi @dan-lee , thank you for creating this PR. 
Can you please rebase and add a changeset file?

**Comment by dan-lee** [comment]
Hey, @dotansimha. After some trouble with rebasing, I finally got it done. Should be ready to merge :)

**Pull request merged**
