### PR TITLE
Add pointer to TypedDocumentNode plugin in vue plugin

### PR DESCRIPTION
**Pull request by tobiasdiez**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

I spent quite some time trying to figure out how to use the plugins TypedDocumentNode and vue-apollo together. Only after finding https://the-guild.dev/blog/typed-document-node, I realized that the latter is no longer needed when using TypedDocumentNode, and that this plugin is the "recommended"/modern version.
Thus, I've added a small note to the documentation pointing others in this direction.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:
- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @tobiasdiez !

**Comment by ferm10n** [comment]
I'm not sure it makes sense to say this plugin is "not recommended"... because isn't the use case for if you're using Vue 3 or Vue 2 + composition-api plugin?

Maybe it'd be better to say "if you're not using the composition functions, use the TypedDocumentNode and vue-apollo" thing

**Comment by tobiasdiez** [comment]
In my experience the Typed Document Node works perfectly well with the composition api.

**Comment by zorji** [comment]
I disagree with this PR. @tobiasdiez @dotansimha 

The goal of `typescript-vue-apollo` is to generate the code and make things automated.

With only TypeDocumentedNode, I have to
- import the variables types
- import the return types
- import the generate document type
- implement `useQuery` or `useMutation` myself and must ensure I did them correctly

With `typescript-vue-apollo`, I just need to import `useXXXQuery` and things work for me.

if you take https://the-guild.dev/blog/typed-document-node as the example, then `typescript-vue-apollo` is one step further to automate and optimise the flow after the 2020 way. The generated code is already using the best practice. When you are using `TypeDocumentedNode` and implementing them yourself, you basically doing the same thing that can be generated. (but in your own style)

I don't think this should be labelled as unrecommended and please consider revert the change.

**Comment by dotansimha** [comment]
> * import the variables types
> * import the return types
> * import the generate document type
> * implement `useQuery` or `useMutation` myself and must ensure I did them correctly

With TypedDocumentNode, you only need to import the generated document object and pass it to your client. If the client supports TypedDocumentNode, you should get type inference for the variables and for the return type, and you don't need to import / manually specify any TS type at all. 

Regrading the hooks - The reason we generated them in other plugins is that we wanted to "burn" the types in and provide a ready-to-use hook. With TypedDocuementNode you get the types automatically, so all you need to do is to use the original hook, and just add your object, and all types are inferred. So no need for additional wrapping.

**Comment by zorji** [comment]
> > * import the variables types
> > * import the return types
> > * import the generate document type
> > * implement `useQuery` or `useMutation` myself and must ensure I did them correctly
> 
> With TypedDocumentNode, you only need to import the generated document object and pass it to your client. If the client supports TypedDocumentNode, you should get type inference for the variables and for the return type, and you don't need to import / manually specify any TS type at all.
> 
> Regarding the hooks - The reason we generated them in other plugins is that we wanted to "burn" the types in and provide a ready-to-use hook. With TypedDocuementNode you get the types automatically, so all you need to do is to use the original hook, and just add your object, and all types are inferred. So no need for additional wrapping.

Thanks @dotansimha I found why it doesn't work for me.
I am using @vue/composition-api, and using @vue/composition-api@4.0.0-alpha.12

In the doc https://github.com/dotansimha/graphql-typed-document-node#with-patch says it's supported in alpha.13 (the latest is alpha.14)

I'll create a PR to update that docs

**Comment by zorji** [comment]
https://github.com/dotansimha/graphql-typed-document-node/pull/107

**Comment by dotansimha** [comment]
> [dotansimha/graphql-typed-document-node#108](https://github.com/dotansimha/graphql-typed-document-node/pull/108)

Awesome! Thank you! :)

**Pull request merged**
