### PR TITLE
Fixed DocumentNodeVariable

### PR DESCRIPTION
**Pull request by alexkharech**

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @alexkharech , thank you for this PR. Can you please share more background about this issue? what does this fix? do we have an issue for tracking the progress on that?

**Comment by alexkharech** [comment]
@dotansimha 
These are two commits to different plugins:
`graphql-request` - will add import type prefixes if used
`vue-apollo` - adds **documentVariableSuffix** and names of imported operations according to general parameters, it doesn't work in current version

This fixes compatibility issues with importing types from another module 
```yml
preset: import-types
presetConfig:
      typesPath: ./types
```

**Comment by dotansimha** [comment]
Got it, thank you @alexkharech. 
Can you please separate this PR to two different PRs? we are trying to minimize PR and changes to the bare minimum, and in this case it seems like the changes to the 2 plugins are unrelated?

**Comment by dotansimha** [comment]
@alexkharech I'm closing this one, let me know if it needs to be reopened (see my latest comment). Thanks!

**Pull request closed without merging**
