### PR TITLE
feat: only typescript operation types plugin

### PR DESCRIPTION
**Pull request by Stonepaw**
## Description

Adds a typescript-operation-types plugin that generates only the types used in operations. This solves the issue where using preResolveTypes and onlyOperationTypes outputs all input and enum types.

I wrote this as a seperate plugin as I felt that adding this complexity to the typescript plugin was overstepping what I can offer and I initially wrote this plugin for use in a mono-repository project that splits out the graphql schema into several packages.

Related #4562 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have constructed a test suite for the plugin that verifies that the correct output is generated in the following cases:

- outputs all nested inputs from the arguments of the queries and mutations
- outputs input enums in various permutations of nesting
- outputs models when omitObjectTypes is false.
- outputs all nested models when omitObjectTypes is false
- outputs only enums and inputs when omitObjectTypes is true
- outputs unions when in the nested object types
- outputs interfaces when in the operation object types
- outputs only used enums in the operation input and object types

**Test Environment**:
- OS: OSX 12.2.1
- `@graphql-codegen/...`: 
- NodeJS: 14

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

I was somewhat unsure of the best way to add this functionality so I opted for a new plugin. This does not need to be merged as is and I'm looking forward to any input on adding this functionality to the code generator.

As a background, my day to day job uses a large monorepository utlizing nx so having a way to split out a massive genereated types library with only the enum and inputs types necessary is becoming essential.

### CODE REVIEW

**Comment by qortex** [comment]
Hitting the same Nx use case, hope it can be merged soon. Or how do you use the plugin by itself in your project?

**Comment by Stonepaw** [comment]
> Hitting the same Nx use case, hope it can be merged soon. Or how do you use the plugin by itself in your project?

I ended up publishing this as standalone npm package for our use as I'm not sure what else needs to be done to get this into master or who needs to review it.

https://www.npmjs.com/package/graphql-codegen-typescript-operation-types

**Comment by matt-kunze-nutrien** [comment]
Throwing my 2c in as well, it would be awesome to see this included in the base project. This is a significant improvement in how operation types are emitted in larger projects where access to the graph is broken apart across multiple packages.

**Comment by charlypoly** [comment]
Hi @Stonepaw!

Thank you for your contribution! ⚡ 

We actually have a project planned for later this year of refactoring the way plugins operate, with better architecture and different usage of the visitor pattern.
This refactoring will be started as a **pilot on a new plugin that shares many goals with this PR**, a new plugin optimized for client-side usage, only keeping the types used in the defined operations.

For this reason, we don't plan to merge your new plugin in the main repo; however, we can still add it in the plugin search (with a dedicated plugin doc page) while keeping it in your `graphql-codegen-typescript-operation-types` package.

We will, of course, keep you all updated on the progress of this new client-side-focused plugin.

Let me know if you need any guidance to add your package to the plugins documentation.

**Pull request closed without merging**
