### PR TITLE
Print file path and number of errors when validating queries against schema

### LINKED ISSUE #621: When validating queries against schema, print the file name with error.
**Is your feature request related to a problem? Please describe.**
When I change my schema I get a lot of validation errors which is very good. This helps me refactor the schema! However having 100 errors withouts specification in which files is frustrating.

**Describe the solution you'd like**
In addition to the validation error, also print the file name in which the error occured.

**Describe alternatives you've considered**
Manually checking every field in every query in every file to see if they have caused one of the errors.

### PR DESCRIPTION
**Pull request by jonaskello**
This is an attempt to solve #621.

I have not been able to test it. Is there some easy way to test?

Fixes #621.

### CODE REVIEW

**Comment by dotansimha** [comment]
Thanks @jonaskello ! Looks good! 
I can help with some basic tests, can you please make sure you allowed edit from maintainers? (https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by jonaskello** [comment]
Thanks! 👍 
Allow edits from maintainers was checked. And I unchecked and checked it again just to be safe :-).

**Comment by dotansimha** [comment]
@jonaskello added tests :) 
some tests for the function that returns the errors, and tests for the cli to tests that it's actually displaying the error correctly and running `process.exit` :)

**Comment by dotansimha** [comment]
Thanks @jonaskello :)

**Pull request merged**
