### PR TITLE
[typescript/flow] Escape enum values defined in GraphQLSchema correctly

### PR DESCRIPTION
**Pull request by dotansimha**
Related: https://github.com/dotansimha/graphql-code-generator/issues/5360

### CODE REVIEW

**Comment by cometkim** [comment]
Hello @dotanSimha It seems that there is a type error not detected by TypeScript here.

https://github.com/cometkim/gatsby-plugin-typegen/issues/143

**Comment by dotansimha** [comment]
Thanks @cometkim , working on a fix :)

**Comment by dotansimha** [comment]
@cometkim should be fixed by https://github.com/dotansimha/graphql-code-generator/commit/7cc37da85feeaf1aee26fde49472d8136b0be2d2 , i'll release it in a few minutes :)

**Comment by dotansimha** [comment]
@cometkim should be fixed in `@graphql-codegen/flow@1.18.4`, can you please try?

**Comment by cometkim** [comment]
@dotansimha Is this change only affect flow? I guess @tony is using TypeScript.

@tony Can you please help to confirm this is fixed? or can you share your project configuration? I can't reproduce the issue in the latest version of the gatsby starter.

**Comment by tony** [comment]
@cometkim I may not be able to get to this until tomorrow (same time)

When I do, Will there be a new version of `gatsby-plugin-typegen` to try again? Or should I pin `@graphql-codegen/flow`?

**Comment by cometkim** [comment]
https://github.com/cometkim/gatsby-plugin-typegen/issues/143#issuecomment-767611740

**Comment by dotansimha** [comment]
> @cometkim I may not be able to get to this until tomorrow (same time)
> 
> 
> 
> When I do, Will there be a new version of `gatsby-plugin-typegen` to try again? Or should I pin `@graphql-codegen/flow`?

Should fix both :)

**Comment by cometkim** [comment]
@dotansimha Another issue reported on the same path. `[object Object]` appears in the stacktrace :thinking: 

https://github.com/cometkim/gatsby-plugin-typegen/issues/143#issuecomment-767681411

**Comment by cometkim** [comment]
Hmm, I see...

https://github.com/dotansimha/graphql-code-generator/blob/49242c20cd985addba5f74442d435a527bdbe163/packages/plugins/other/visitor-plugin-common/src/types.ts#L21-L23

The definition of `EnumTypesMap` is telling that the value could be a number. I think this might be the case:

```js
new GraphQLEnumType({
  name: 'RGB',
  values: {
    RED: { value: 0 },
    GREEN: { value: 1 },
    BLUE: { value: 2 }
  }
});
```

The graphql-codegen core API does not restrict the inclusion of user-created enum objects in the input schema. We cannot assume that there will always be only strings.

**Comment by cometkim** [comment]
https://graphql.org/graphql-js/type/#graphqlenumtype

> GraphQL serializes Enum values as strings, however internally Enums can be represented by any kind of type, often integers.

@dotansimha Can we provide meaningful artifacts even if it's not a string? Otherwise, I think it would be the correct behavior to ignore them all.

**Pull request merged**
