### PR TITLE
More verbose error logging for document validation

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Should fix part of #925, where it would normally just display "Found N error(s) in your documents", now shows file, line and column, along with the error message.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@dotansimha I just now see that you mentioned @DAB0mB working on something like this. I was working on this yesterday but only just now created the PR. Let me know what you want to do.

**Comment by ardatan** [comment]
Thank you @jeroenvisser101 !
I think we should move make this change in `checkValidationErrors` instead of removing it.
https://github.com/ardatan/graphql-toolkit/blob/8858a0a1116bc7236a6f29e7c1c3723cd5be4720/src/utils/validate-documents.ts#L20

**Comment by jeroenvisser101** [comment]
@ardatan I actually also started on that, but I actually want to throw a DetailedError, and I believe that comes from graphql-code-generator. That's why I chose to re-implement the method (although altered) in the core.

**Comment by dotansimha** [comment]
Thank you @jeroenvisser101 ! 
@DAB0mB is working on adding unit tests to reproduce it and fixing this issue in `graphql-toolkit`, and he takes inspiration from your solution.

**Comment by jeroenvisser101** [comment]
@dotansimha thank you! :)

**Pull request closed without merging**
