### PR TITLE
fix(typescript-operations): wrong type for variable with default value ( #1934)

### PR DESCRIPTION
**Pull request by n1ru4l**
Related #1934

`typescript-operations` generates false types for operation variables width default values.

Example:

```graphql
query foo($var: String = "test") {
  foo(var: $var)
}
```

**Generated Types:**

```typescript
export type FooQueryVariables = {
  var: Maybe<Scalars['String']>
};
```

**Expected Types:**

```diff
export type FooQueryVariables = {
-  var: Maybe<Scalars['String']>
+  var?: Maybe<Scalars['String']>
};
```

More details can be found in https://github.com/dotansimha/graphql-code-generator/issues/1934

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @n1ru4l ! Thank you for this PR.
I think we can even drop `TypeScriptOperationVariablesToObject` and use `TSOperationVariablesToObject` directly.

The base implementation of `TSOperationVariablesToObject#formatTypeString` does:

```ts
  protected formatFieldString(fieldName: string, isNonNullType: boolean, hasDefaultValue: boolean): string {
    if (hasDefaultValue || isNonNullType || this._avoidOptionals) {
      return fieldName;
    } else {
      return `${fieldName}?`;
    }
  }
```

And then, the `TypeScriptOperationVariablesToObject#formatTypeString` overrides it with: 

```ts
  protected formatTypeString(fieldType: string, isNonNullType: boolean, hasDefaultValue: boolean): string {
    return fieldType;
  }
```

Maybe the subclass is not even necessary there? and we can use the same one? I can't really remember, I think we should check that.

**Comment by n1ru4l** [comment]
@dotansimha I changed the implementation, I still have some concerns about the `avoidOptionals` option.

What should be the correct output (given `avoidOptionals` is set to true):

```graphql
type MyType {
  foo(
    a: String = "default",
    b: String! = "default",
    c: String,
    d: String!
  ): String
}
```

Output 1

```ts
export type MyTypeFooArgs = {
  a: Maybe<Scalars['String']> | undefined,
  b: Scalars['String'] | undefined,
  c: Maybe<Scalars['String']>,
  d: Scalars['String']
};
```

Output 2

```ts
export type MyTypeFooArgs = {
  a?: Maybe<Scalars['String']>,
  b?: Scalars['String'],
  c: Maybe<Scalars['String']>,
  d: Scalars['String']
};

**Comment by dotansimha** [comment]
@n1ru4l , I think we can keep those as optionals, because we can be sure that GraphQL engine will make sure to fill in the default value. 
The reason we chose to use `avoid` keyword is to keep us the option to generate optionals in some cases. 

I think option 2 is better :) 

Thank you for your work on this PR!

**Comment by n1ru4l** [comment]
@dotansimha That makes sense to me 😊

I added a test and altered the implementation! Let me know what you think about it!

**Comment by dotansimha** [comment]
Looks great! Thank you @n1ru4l !

**Comment by n1ru4l** [comment]
@dotansimha Thank you for guiding me  🎉

**Pull request merged**
