### PR TITLE
fix: gqlMagicComment type

### PR DESCRIPTION
**Pull request by rwu823**
## Description

fix incorrect type.

Related #8579 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## Checklist:

- [X] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by rwu823** [comment]
@saihaj Added.

**Review by saihaj — APPROVED** [review]

**Comment by saihaj** [comment]
@rwu823 looks like prettier is failing

**Comment by rwu823** [comment]
@saihaj `next.config.mjs` It looks not my modification.

image

And I tried run `prettier:check` on my local is passed. Could you help to re-run it?

image

**Comment by saihaj** [comment]
thanks @rwu823

**Pull request merged**
